<?php

namespace AdOceanSdk\Kernel\Interface;

/**
 * OpenApi public surface — generated.
 * Implemented by \AdOceanSdk\OpenApi via OpenApiMethodsTrait.
 * @generated by script/gen_api_open.php
 */
interface OpenApiInterface
{
    /**
     * 批量查询账户余额
     * https://open.oceanengine.com/labels/7/docs/1799006604968971
     */
    public function openAccountFundGetGetApi(\AdOceanSdk\Fund\Params\AccountFundGetGetParams|array $params = []): \AdOceanSdk\Fund\Response\AccountFundGetGetResponse;

    /**
     * 获取素材派生数据（计划维度）
     * https://open.oceanengine.com/labels/7/docs/1755177028152324
     */
    public function openAdMetricsGetGetApi(\AdOceanSdk\Advertising\Params\AdMetricsGetGetParams|array $params = []): \AdOceanSdk\Advertising\Response\AdMetricsGetGetResponse;

    /**
     * 引流下单转化信息获取
     * https://open.oceanengine.com/labels/7/docs/1774836168252548
     */
    public function openAdvConvertOleConvertPostApi(\AdOceanSdk\Tools\Params\AdvConvertOleConvertPostParams|array $params = []): \AdOceanSdk\Tools\Response\AdvConvertOleConvertPostResponse;

    /**
     * 获取广告主账户头像
     * https://open.oceanengine.com/labels/7/docs/1696710512904192
     */
    public function openAdvertiserAvatarGetApi(\AdOceanSdk\Advertiser\Params\AdvertiserAvatarGetParams|array $params = []): \AdOceanSdk\Advertiser\Response\AdvertiserAvatarGetResponse;

    /**
     * 更新广告主账户头像
     * https://open.oceanengine.com/labels/7/docs/1696710512435215
     */
    public function openAdvertiserAvatarSubmitPostApi(\AdOceanSdk\Advertiser\Params\AdvertiserAvatarSubmitPostParams|array $params = []): \AdOceanSdk\Advertiser\Response\AdvertiserAvatarSubmitPostResponse;

    /**
     * 获取广告主账户头像ID
     * https://open.oceanengine.com/labels/7/docs/1794039016601604
     */
    public function openAdvertiserAvatarUploadPostApi(\AdOceanSdk\Advertiser\Params\AdvertiserAvatarUploadPostParams|array $params = []): \AdOceanSdk\Advertiser\Response\AdvertiserAvatarUploadPostResponse;

    /**
     * 获取账户日预算
     * https://open.oceanengine.com/labels/7/docs/1696710531128335
     */
    public function openAdvertiserBudgetGetApi(\AdOceanSdk\Advertising\Params\AdvertiserBudgetGetParams|array $params = []): \AdOceanSdk\Advertising\Response\AdvertiserBudgetGetResponse;

    /**
     * 更新账户日预算
     * https://open.oceanengine.com/labels/7/docs/1696710531631116
     */
    public function openAdvertiserBudgetUpdatePostApi(\AdOceanSdk\Advertising\Params\AdvertiserBudgetUpdatePostParams|array $params = []): \AdOceanSdk\Advertising\Response\AdvertiserBudgetUpdatePostResponse;

    /**
     * 查询推广产品资质规则配置
     * https://open.oceanengine.com/labels/7/docs/1776710970860551
     */
    public function openAdvertiserDeliveryPkgConfigGetApi(\AdOceanSdk\Advertiser\Params\AdvertiserDeliveryPkgConfigGetParams|array $params = []): \AdOceanSdk\Advertiser\Response\AdvertiserDeliveryPkgConfigGetResponse;

    /**
     * 查询推广产品资质
     * https://open.oceanengine.com/labels/7/docs/1776711148266572
     */
    public function openAdvertiserDeliveryPkgGetApi(\AdOceanSdk\Advertiser\Params\AdvertiserDeliveryPkgGetParams|array $params = []): \AdOceanSdk\Advertiser\Response\AdvertiserDeliveryPkgGetResponse;

    /**
     * 提交/编辑推广产品资质
     * https://open.oceanengine.com/labels/7/docs/1776711210685572
     */
    public function openAdvertiserDeliveryPkgSubmitPostApi(\AdOceanSdk\Advertiser\Params\AdvertiserDeliveryPkgSubmitPostParams|array $params = []): \AdOceanSdk\Advertiser\Response\AdvertiserDeliveryPkgSubmitPostResponse;

    /**
     * 查询投放资质（新版）
     * https://open.oceanengine.com/labels/7/docs/1761500990156815
     */
    public function openAdvertiserDeliveryQualificationListGetApi(\AdOceanSdk\Advertiser\Params\AdvertiserDeliveryQualificationListGetParams|array $params = []): \AdOceanSdk\Advertiser\Response\AdvertiserDeliveryQualificationListGetResponse;

    /**
     * 提交投放资质（新版）
     * https://open.oceanengine.com/labels/7/docs/1761501324513352
     */
    public function openAdvertiserDeliveryQualificationSubmitPostApi(\AdOceanSdk\Advertiser\Params\AdvertiserDeliveryQualificationSubmitPostParams|array $params = []): \AdOceanSdk\Advertiser\Response\AdvertiserDeliveryQualificationSubmitPostResponse;

    /**
     * 查询账户日流水
     * https://open.oceanengine.com/labels/7/docs/1696710526682112
     */
    public function openAdvertiserFundDailyStatGetApi(\AdOceanSdk\Advertiser\Params\AdvertiserFundDailyStatGetParams|array $params = []): \AdOceanSdk\Advertiser\Response\AdvertiserFundDailyStatGetResponse;

    /**
     * 查询账号余额
     * https://open.oceanengine.com/labels/7/docs/1696710526192652
     */
    public function openAdvertiserFundGetApi(\AdOceanSdk\Advertiser\Params\AdvertiserFundGetParams|array $params = []): \AdOceanSdk\Advertiser\Response\AdvertiserFundGetResponse;

    /**
     * 查询账号流水明细
     * https://open.oceanengine.com/labels/7/docs/1696710527205388
     */
    public function openAdvertiserFundTransactionGetApi(\AdOceanSdk\Advertiser\Params\AdvertiserFundTransactionGetParams|array $params = []): \AdOceanSdk\Advertiser\Response\AdvertiserFundTransactionGetResponse;

    /**
     * 获取广告主信息
     * https://open.oceanengine.com/labels/7/docs/1696710508983311
     */
    public function openAdvertiserInfoGetApi(\AdOceanSdk\Advertiser\Params\AdvertiserInfoGetParams|array $params = []): \AdOceanSdk\Advertiser\Response\AdvertiserInfoGetResponse;

    /**
     * 获取广告主公开信息
     * https://open.oceanengine.com/labels/7/docs/1696710511950860
     */
    public function openAdvertiserPublicInfoGetApi(\AdOceanSdk\Advertiser\Params\AdvertiserPublicInfoGetParams|array $params = []): \AdOceanSdk\Advertiser\Response\AdvertiserPublicInfoGetResponse;

    /**
     * 获取主体资质（新版）
     * https://open.oceanengine.com/labels/7/docs/1743294338713611
     */
    public function openAdvertiserQualificationGetApi(\AdOceanSdk\Advertiser\Params\AdvertiserQualificationGetParams|array $params = []): \AdOceanSdk\Advertiser\Response\AdvertiserQualificationGetResponse;

    /**
     * 提交主体资质（新版）
     * https://open.oceanengine.com/labels/7/docs/1743294661429259
     */
    public function openAdvertiserQualificationSubmitPostApi(\AdOceanSdk\Advertiser\Params\AdvertiserQualificationSubmitPostParams|array $params = []): \AdOceanSdk\Advertiser\Response\AdvertiserQualificationSubmitPostResponse;

    /**
     * 查询账户可转余额
     * https://open.oceanengine.com/labels/7/docs/1725634464247879
     */
    public function openAdvertiserTransferableFundGetApi(\AdOceanSdk\Advertiser\Params\AdvertiserTransferableFundGetParams|array $params = []): \AdOceanSdk\Advertiser\Response\AdvertiserTransferableFundGetResponse;

    /**
     * 修改广告主信息
     * https://open.oceanengine.com/labels/7/docs/1696710517205007
     */
    public function openAdvertiserUpdatePostApi(\AdOceanSdk\Advertiser\Params\AdvertiserUpdatePostParams|array $params = []): \AdOceanSdk\Advertiser\Response\AdvertiserUpdatePostResponse;

    /**
     * 广告主账户复制
     * https://open.oceanengine.com/labels/7/docs/1775097300794371
     */
    public function openAgentAdvertiserCopyPostApi(\AdOceanSdk\Agent\Params\AgentAdvertiserCopyPostParams|array $params = []): \AdOceanSdk\Agent\Response\AgentAdvertiserCopyPostResponse;

    /**
     * 代理商管理账户列表
     * https://open.oceanengine.com/labels/7/docs/1696710516003852
     */
    public function openAgentAdvertiserSelectGetApi(\AdOceanSdk\Agent\Params\AgentAdvertiserSelectGetParams|array $params = []): \AdOceanSdk\Agent\Response\AgentAdvertiserSelectGetResponse;

    /**
     * 二级代理商列表
     * https://open.oceanengine.com/labels/7/docs/1696710517693452
     */
    public function openAgentChildAgentSelectGetApi(\AdOceanSdk\Agent\Params\AgentChildAgentSelectGetParams|array $params = []): \AdOceanSdk\Agent\Response\AgentChildAgentSelectGetResponse;

    /**
     * 获取代理商信息
     * https://open.oceanengine.com/labels/7/docs/1696710518158351
     */
    public function openAgentInfoGetApi(\AdOceanSdk\Agent\Params\AgentInfoGetParams|array $params = []): \AdOceanSdk\Agent\Response\AgentInfoGetResponse;

    /**
     * 提交退款交易号（方舟）
     * https://open.oceanengine.com/labels/7/docs/1766755445237824
     */
    public function openAgentRefundTransferSeqCommitPostApi(\AdOceanSdk\Fund\Params\AgentRefundTransferSeqCommitPostParams|array $params = []): \AdOceanSdk\Fund\Response\AgentRefundTransferSeqCommitPostResponse;

    /**
     * 创建退款交易号（方舟）
     * https://open.oceanengine.com/labels/7/docs/1766755414170636
     */
    public function openAgentRefundTransferSeqCreatePostApi(\AdOceanSdk\Fund\Params\AgentRefundTransferSeqCreatePostParams|array $params = []): \AdOceanSdk\Fund\Response\AgentRefundTransferSeqCreatePostResponse;

    /**
     * 提交转账交易号（方舟）
     * https://open.oceanengine.com/labels/7/docs/1766755371753487
     */
    public function openAgentTransferSeqCommitPostApi(\AdOceanSdk\Fund\Params\AgentTransferSeqCommitPostParams|array $params = []): \AdOceanSdk\Fund\Response\AgentTransferSeqCommitPostResponse;

    /**
     * 创建转账交易号（方舟）
     * https://open.oceanengine.com/labels/7/docs/1766755293435980
     */
    public function openAgentTransferSeqCreatePostApi(\AdOceanSdk\Fund\Params\AgentTransferSeqCreatePostParams|array $params = []): \AdOceanSdk\Fund\Response\AgentTransferSeqCreatePostResponse;

    /**
     * 查询代理商转账记录
     * https://open.oceanengine.com/labels/7/docs/1795124749017235
     */
    public function openAgentTransferTransactionRecordGetApi(\AdOceanSdk\Fund\Params\AgentTransferTransactionRecordGetParams|array $params = []): \AdOceanSdk\Fund\Response\AgentTransferTransactionRecordGetResponse;

    /**
     * 创建异步任务
     * https://open.oceanengine.com/labels/7/docs/1696710562799616
     */
    public function openAsyncTaskCreatePostApi(\AdOceanSdk\Report\Params\AsyncTaskCreatePostParams|array $params = []): \AdOceanSdk\Report\Response\AsyncTaskCreatePostResponse;

    /**
     * 下载任务结果
     * https://open.oceanengine.com/labels/7/docs/1696710563878927
     */
    public function openAsyncTaskDownloadGetApi(\AdOceanSdk\Report\Params\AsyncTaskDownloadGetParams|array $params = []): \AdOceanSdk\Report\Response\AsyncTaskDownloadGetResponse;

    /**
     * 获取任务列表
     * https://open.oceanengine.com/labels/7/docs/1696710563323916
     */
    public function openAsyncTaskGetApi(\AdOceanSdk\Report\Params\AsyncTaskGetParams|array $params = []): \AdOceanSdk\Report\Response\AsyncTaskGetResponse;

    /**
     * 创建定向包
     * https://open.oceanengine.com/labels/7/docs/1696710735901711
     */
    public function openAudiencePackageCreatePostApi(\AdOceanSdk\Tools\Params\AudiencePackageCreatePostParams|array $params = []): \AdOceanSdk\Tools\Response\AudiencePackageCreatePostResponse;

    /**
     * 删除定向包
     * https://open.oceanengine.com/labels/7/docs/1696710732991488
     */
    public function openAudiencePackageDeletePostApi(\AdOceanSdk\Tools\Params\AudiencePackageDeletePostParams|array $params = []): \AdOceanSdk\Tools\Response\AudiencePackageDeletePostResponse;

    /**
     * 获取定向包
     * https://open.oceanengine.com/labels/7/docs/1696710731761676
     */
    public function openAudiencePackageGetApi(\AdOceanSdk\Tools\Params\AudiencePackageGetParams|array $params = []): \AdOceanSdk\Tools\Response\AudiencePackageGetResponse;

    /**
     * 更新定向包
     * https://open.oceanengine.com/labels/7/docs/1696710732349455
     */
    public function openAudiencePackageUpdatePostApi(\AdOceanSdk\Tools\Params\AudiencePackageUpdatePostParams|array $params = []): \AdOceanSdk\Tools\Response\AudiencePackageUpdatePostResponse;

    /**
     * 创建预算组
     * https://open.oceanengine.com/labels/7/docs/1780159359081540
     */
    public function openBudgetGroupCreatePostApi(\AdOceanSdk\Advertising\Params\BudgetGroupCreatePostParams|array $params = []): \AdOceanSdk\Advertising\Response\BudgetGroupCreatePostResponse;

    /**
     * 批量删除预算组
     * https://open.oceanengine.com/labels/7/docs/1780643886635008
     */
    public function openBudgetGroupDeletePostApi(\AdOceanSdk\Advertising\Params\BudgetGroupDeletePostParams|array $params = []): \AdOceanSdk\Advertising\Response\BudgetGroupDeletePostResponse;

    /**
     * 获取预算组列表
     * https://open.oceanengine.com/labels/7/docs/1780644067911818
     */
    public function openBudgetGroupListGetApi(\AdOceanSdk\Advertising\Params\BudgetGroupListGetParams|array $params = []): \AdOceanSdk\Advertising\Response\BudgetGroupListGetResponse;

    /**
     * 获取主体下的账户列表
     * https://open.oceanengine.com/labels/7/docs/1741479196149775
     */
    public function openBusinessPlatformCompanyAccountGetApi(\AdOceanSdk\Majordomo\Params\BusinessPlatformCompanyAccountGetParams|array $params = []): \AdOceanSdk\Majordomo\Response\BusinessPlatformCompanyAccountGetResponse;

    /**
     * 获取纵横组织下所有主体信息
     * https://open.oceanengine.com/labels/7/docs/1741478619724813
     */
    public function openBusinessPlatformCompanyInfoGetApi(\AdOceanSdk\Majordomo\Params\BusinessPlatformCompanyInfoGetParams|array $params = []): \AdOceanSdk\Majordomo\Response\BusinessPlatformCompanyInfoGetResponse;

    /**
     * 查询合作组织
     * https://open.oceanengine.com/labels/7/docs/1710414874245133
     */
    public function openBusinessPlatformPartnerOrganizationListGetApi(\AdOceanSdk\Majordomo\Params\BusinessPlatformPartnerOrganizationListGetParams|array $params = []): \AdOceanSdk\Majordomo\Response\BusinessPlatformPartnerOrganizationListGetResponse;

    /**
     * 获取关联云图的广告主账户信息
     * https://open.oceanengine.com/labels/7/docs/1768100113310735
     */
    public function openCDPBrandGetApi(\AdOceanSdk\Advertising\Params\CDPBrandGetParams|array $params = []): \AdOceanSdk\Advertising\Response\CDPBrandGetResponse;

    /**
     * 获取广告组
     * https://open.oceanengine.com/labels/7/docs/1696710532657164
     */
    public function openCampaignGetApi(\AdOceanSdk\Advertising\Params\CampaignGetParams|array $params = []): \AdOceanSdk\Advertising\Response\CampaignGetResponse;

    /**
     * 获取同主体下广告主图文素材
     * https://open.oceanengine.com/labels/7/docs/1773560989475840
     */
    public function openCarouselAdGetApi(\AdOceanSdk\File\Params\CarouselAdGetParams|array $params = []): \AdOceanSdk\File\Response\CarouselAdGetResponse;

    /**
     * 上传图文
     * https://open.oceanengine.com/labels/7/docs/1773552433235140
     */
    public function openCarouselCreatePostApi(\AdOceanSdk\File\Params\CarouselCreatePostParams|array $params = []): \AdOceanSdk\File\Response\CarouselCreatePostResponse;

    /**
     * 批量删除图文
     * https://open.oceanengine.com/labels/7/docs/1773561744826380
     */
    public function openCarouselDeletePostApi(\AdOceanSdk\File\Params\CarouselDeletePostParams|array $params = []): \AdOceanSdk\File\Response\CarouselDeletePostResponse;

    /**
     * 获取图文素材
     * https://open.oceanengine.com/labels/7/docs/1773554026740736
     */
    public function openCarouselListGetApi(\AdOceanSdk\File\Params\CarouselListGetParams|array $params = []): \AdOceanSdk\File\Response\CarouselListGetResponse;

    /**
     * 更新图文信息
     * https://open.oceanengine.com/labels/7/docs/1773554529716228
     */
    public function openCarouselUpdatePostApi(\AdOceanSdk\File\Params\CarouselUpdatePostParams|array $params = []): \AdOceanSdk\File\Response\CarouselUpdatePostResponse;

    /**
     * 工作台转账-获取最大可转余额
     * https://open.oceanengine.com/labels/7/docs/1816052561374300
     */
    public function openCgTransferCanTransferBalanceGetApi(\AdOceanSdk\Fund\Params\CgTransferCanTransferBalanceGetParams|array $params = []): \AdOceanSdk\Fund\Response\CgTransferCanTransferBalanceGetResponse;

    /**
     * 工作台转账-获取可转列表
     * https://open.oceanengine.com/labels/7/docs/1816052658391124
     */
    public function openCgTransferCanTransferTargetListGetApi(\AdOceanSdk\Fund\Params\CgTransferCanTransferTargetListGetParams|array $params = []): \AdOceanSdk\Fund\Response\CgTransferCanTransferTargetListGetResponse;

    /**
     * 工作台转账-查询账户转账余额
     * https://open.oceanengine.com/labels/7/docs/1816052431206464
     */
    public function openCgTransferTransferBalanceGetApi(\AdOceanSdk\Fund\Params\CgTransferTransferBalanceGetParams|array $params = []): \AdOceanSdk\Fund\Response\CgTransferTransferBalanceGetResponse;

    /**
     * 工作台转账-发起转账
     * https://open.oceanengine.com/labels/7/docs/1816052723776516
     */
    public function openCgTransferTransferCreatePostApi(\AdOceanSdk\Fund\Params\CgTransferTransferCreatePostParams|array $params = []): \AdOceanSdk\Fund\Response\CgTransferTransferCreatePostResponse;

    /**
     * 工作台转账-查询转账单信息
     * https://open.oceanengine.com/labels/7/docs/1816052335753539
     */
    public function openCgTransferTransferDetailGetApi(\AdOceanSdk\Fund\Params\CgTransferTransferDetailGetParams|array $params = []): \AdOceanSdk\Fund\Response\CgTransferTransferDetailGetResponse;

    /**
     * 新建或修改配置，并保存到计划
     * https://open.oceanengine.com/labels/7/docs/1736244450483215
     */
    public function openCreativeAutoGenerateConfigCreatePostApi(\AdOceanSdk\Advertising\Params\CreativeAutoGenerateConfigCreatePostParams|array $params = []): \AdOceanSdk\Advertising\Response\CreativeAutoGenerateConfigCreatePostResponse;

    /**
     * 创意详细信息（新）
     * https://open.oceanengine.com/labels/7/docs/1742668551117827
     */
    public function openCreativeDetailGetApi(\AdOceanSdk\Advertising\Params\CreativeDetailGetParams|array $params = []): \AdOceanSdk\Advertising\Response\CreativeDetailGetResponse;

    /**
     * 获取创意列表
     * https://open.oceanengine.com/labels/7/docs/1696710540735500
     */
    public function openCreativeGetApi(\AdOceanSdk\Advertising\Params\CreativeGetParams|array $params = []): \AdOceanSdk\Advertising\Response\CreativeGetResponse;

    /**
     * 获取素材派生数据（素材维度）
     * https://open.oceanengine.com/labels/7/docs/1755177023094787
     */
    public function openCreativeMaterialMetricsGetApi(\AdOceanSdk\Advertising\Params\CreativeMaterialMetricsGetParams|array $params = []): \AdOceanSdk\Advertising\Response\CreativeMaterialMetricsGetResponse;

    /**
     * 获取创意审核建议
     * https://open.oceanengine.com/labels/7/docs/1696710544068620
     */
    public function openCreativeRejectReasonGetApi(\AdOceanSdk\Advertising\Params\CreativeRejectReasonGetParams|array $params = []): \AdOceanSdk\Advertising\Response\CreativeRejectReasonGetResponse;

    /**
     * 获取模板（白盒策略）列表
     * https://open.oceanengine.com/labels/7/docs/1758356001909828
     */
    public function openCreativeStrategyListGetApi(\AdOceanSdk\Advertising\Params\CreativeStrategyListGetParams|array $params = []): \AdOceanSdk\Advertising\Response\CreativeStrategyListGetResponse;

    /**
     * 获取模板详情
     * https://open.oceanengine.com/labels/7/docs/1736243716320256
     */
    public function openCreativeTemplateDetailGetGetApi(\AdOceanSdk\Advertising\Params\CreativeTemplateDetailGetGetParams|array $params = []): \AdOceanSdk\Advertising\Response\CreativeTemplateDetailGetGetResponse;

    /**
     * 获取模板列表
     * https://open.oceanengine.com/labels/7/docs/1736241054353421
     */
    public function openCreativeTemplateListGetApi(\AdOceanSdk\Advertising\Params\CreativeTemplateListGetParams|array $params = []): \AdOceanSdk\Advertising\Response\CreativeTemplateListGetResponse;

    /**
     * 获取模板标签列表
     * https://open.oceanengine.com/labels/7/docs/1736241004382219
     */
    public function openCreativeTemplateTagsGetApi(\AdOceanSdk\Advertising\Params\CreativeTemplateTagsGetParams|array $params = []): \AdOceanSdk\Advertising\Response\CreativeTemplateTagsGetResponse;

    /**
     * 更改创意状态
     * https://open.oceanengine.com/labels/7/docs/1696710543049740
     */
    public function openCreativeUpdateStatusPostApi(\AdOceanSdk\Advertising\Params\CreativeUpdateStatusPostParams|array $params = []): \AdOceanSdk\Advertising\Response\CreativeUpdateStatusPostResponse;

    /**
     * 人群包列表
     * https://open.oceanengine.com/labels/7/docs/1696710570721295
     */
    public function openCustomAudienceSelectGetApi(\AdOceanSdk\DMP\Params\CustomAudienceSelectGetParams|array $params = []): \AdOceanSdk\DMP\Response\CustomAudienceSelectGetResponse;

    /**
     * 获取纵横组织下资产账户列表（分页）
     * https://open.oceanengine.com/labels/7/docs/1696710520884224
     */
    public function openCustomerCenterAdvertiserListGetApi(\AdOceanSdk\Majordomo\Params\CustomerCenterAdvertiserListGetParams|array $params = []): \AdOceanSdk\Majordomo\Response\CustomerCenterAdvertiserListGetResponse;

    /**
     * 获取可转账户列表（客户中心&广告主）
     * https://open.oceanengine.com/labels/7/docs/1758605359659008
     */
    public function openCustomerCenterAdvertiserTransferableListGetApi(\AdOceanSdk\Fund\Params\CustomerCenterAdvertiserTransferableListGetParams|array $params = []): \AdOceanSdk\Fund\Response\CustomerCenterAdvertiserTransferableListGetResponse;

    /**
     * 提交转账交易号
     * https://open.oceanengine.com/labels/7/docs/1758606542833678
     */
    public function openCustomerCenterFundTransferSeqCommitPostApi(\AdOceanSdk\Fund\Params\CustomerCenterFundTransferSeqCommitPostParams|array $params = []): \AdOceanSdk\Fund\Response\CustomerCenterFundTransferSeqCommitPostResponse;

    /**
     * 创建转账交易号
     * https://open.oceanengine.com/labels/7/docs/1758606134468620
     */
    public function openCustomerCenterFundTransferSeqCreatePostApi(\AdOceanSdk\Fund\Params\CustomerCenterFundTransferSeqCreatePostParams|array $params = []): \AdOceanSdk\Fund\Response\CustomerCenterFundTransferSeqCreatePostResponse;

    /**
     * 删除人群包
     * https://open.oceanengine.com/labels/7/docs/1696710572836879
     */
    public function openDMPCustomAudienceDeletePostApi(\AdOceanSdk\DMP\Params\DMPCustomAudienceDeletePostParams|array $params = []): \AdOceanSdk\DMP\Response\DMPCustomAudienceDeletePostResponse;

    /**
     * 发布人群包
     * https://open.oceanengine.com/labels/7/docs/1696710571768844
     */
    public function openDMPCustomAudiencePublishPostApi(\AdOceanSdk\DMP\Params\DMPCustomAudiencePublishPostParams|array $params = []): \AdOceanSdk\DMP\Response\DMPCustomAudiencePublishPostResponse;

    /**
     * 推送人群包
     * https://open.oceanengine.com/labels/7/docs/1696710572311552
     */
    public function openDMPCustomAudiencePushV2PostApi(\AdOceanSdk\DMP\Params\DMPCustomAudiencePushV2PostParams|array $params = []): \AdOceanSdk\DMP\Response\DMPCustomAudiencePushV2PostResponse;

    /**
     * 人群包详细信息
     * https://open.oceanengine.com/labels/7/docs/1696710571259916
     */
    public function openDMPCustomAudienceReadGetApi(\AdOceanSdk\DMP\Params\DMPCustomAudienceReadGetParams|array $params = []): \AdOceanSdk\DMP\Response\DMPCustomAudienceReadGetResponse;

    /**
     * 数据源文件上传
     * https://open.oceanengine.com/labels/7/docs/1696710568556544
     */
    public function openDMPDataSourceFileUploadPostApi(\AdOceanSdk\DMP\Params\DMPDataSourceFileUploadPostParams|array $params = []): \AdOceanSdk\DMP\Response\DMPDataSourceFileUploadPostResponse;

    /**
     * 获取DPA分类
     * https://open.oceanengine.com/labels/7/docs/1696710580168716
     */
    public function openDPACategoryGetGetApi(\AdOceanSdk\DPA\Params\DPACategoryGetGetParams|array $params = []): \AdOceanSdk\DPA\Response\DPACategoryGetGetResponse;

    /**
     * 获取线索商品详情
     * https://open.oceanengine.com/labels/7/docs/1779436000953415
     */
    public function openDPAClueProductDetailGetApi(\AdOceanSdk\DPA\Params\DPAClueProductDetailGetParams|array $params = []): \AdOceanSdk\DPA\Response\DPAClueProductDetailGetResponse;

    /**
     * 获取线索商品列表
     * https://open.oceanengine.com/labels/7/docs/1779430442685440
     */
    public function openDPAClueProductListGetApi(\AdOceanSdk\DPA\Params\DPAClueProductListGetParams|array $params = []): \AdOceanSdk\DPA\Response\DPAClueProductListGetResponse;

    /**
     * 获取商品列表
     * https://open.oceanengine.com/labels/7/docs/1696710578078732
     */
    public function openDPADetailGetGetApi(\AdOceanSdk\DPA\Params\DPADetailGetGetParams|array $params = []): \AdOceanSdk\DPA\Response\DPADetailGetGetResponse;

    /**
     * 获取商品库元信息
     * https://open.oceanengine.com/labels/7/docs/1696710577566735
     */
    public function openDPAMetaGetGetApi(\AdOceanSdk\DPA\Params\DPAMetaGetGetParams|array $params = []): \AdOceanSdk\DPA\Response\DPAMetaGetGetResponse;

    /**
     * 获取商品库信息
     * https://open.oceanengine.com/labels/7/docs/1696710577036288
     */
    public function openDPAProductAvailablesGetApi(\AdOceanSdk\DPA\Params\DPAProductAvailablesGetParams|array $params = []): \AdOceanSdk\DPA\Response\DPAProductAvailablesGetResponse;

    /**
     * 创建DPA商品（无商品id）
     * https://open.oceanengine.com/labels/7/docs/1726081113859075
     */
    public function openDPAProductCreatePostApi(\AdOceanSdk\DPA\Params\DPAProductCreatePostParams|array $params = []): \AdOceanSdk\DPA\Response\DPAProductCreatePostResponse;

    /**
     * 删除DPA商品
     * https://open.oceanengine.com/labels/7/docs/1726629070419968
     */
    public function openDPAProductDeletePostApi(\AdOceanSdk\DPA\Params\DPAProductDeletePostParams|array $params = []): \AdOceanSdk\DPA\Response\DPAProductDeletePostResponse;

    /**
     * 获取商品详情
     * https://open.oceanengine.com/labels/7/docs/1696710578614272
     */
    public function openDPAProductDetailGetGetApi(\AdOceanSdk\DPA\Params\DPAProductDetailGetGetParams|array $params = []): \AdOceanSdk\DPA\Response\DPAProductDetailGetGetResponse;

    /**
     * 批量修改DPA商品状态
     * https://open.oceanengine.com/labels/7/docs/1726637930114048
     */
    public function openDPAProductStatusBatchUpdatePostApi(\AdOceanSdk\DPA\Params\DPAProductStatusBatchUpdatePostParams|array $params = []): \AdOceanSdk\DPA\Response\DPAProductStatusBatchUpdatePostResponse;

    /**
     * 创建DPA商品（已有商品id）/修改DPA商品
     * https://open.oceanengine.com/labels/7/docs/1726081566816271
     */
    public function openDPAProductUpdatePostApi(\AdOceanSdk\DPA\Params\DPAProductUpdatePostParams|array $params = []): \AdOceanSdk\DPA\Response\DPAProductUpdatePostResponse;

    /**
     * 获取 DPA 商品库视频模板
     * https://open.oceanengine.com/labels/7/docs/1696710582303744
     */
    public function openDPAVideoGetGetApi(\AdOceanSdk\DPA\Params\DPAVideoGetGetParams|array $params = []): \AdOceanSdk\DPA\Response\DPAVideoGetGetResponse;

    /**
     * 获取商品库DPA分类
     * https://open.oceanengine.com/labels/7/docs/1846200236566720?origin=left_nav
     */
    public function openDpaEbpCategoryGetGetApi(\AdOceanSdk\DPA\Params\DpaEbpCategoryGetGetParams|array $params = []): \AdOceanSdk\DPA\Response\DpaEbpCategoryGetGetResponse;

    /**
     * 删除升级版商品
     * https://open.oceanengine.com/labels/7/docs/1846200682152971?origin=left_nav
     */
    public function openDpaEbpClueProductDeletePostApi(\AdOceanSdk\DPA\Params\DpaEbpClueProductDeletePostParams|array $params = []): \AdOceanSdk\DPA\Response\DpaEbpClueProductDeletePostResponse;

    /**
     * 获取升级版商品详情
     * https://open.oceanengine.com/labels/7/docs/1846200329551114?origin=left_nav
     */
    public function openDpaEbpClueProductGetGetApi(\AdOceanSdk\DPA\Params\DpaEbpClueProductGetGetParams|array $params = []): \AdOceanSdk\DPA\Response\DpaEbpClueProductGetGetResponse;

    /**
     * 获取升级版商品列表
     * https://open.oceanengine.com/labels/7/docs/1846200582278283?origin=left_nav
     */
    public function openDpaEbpClueProductListGetApi(\AdOceanSdk\DPA\Params\DpaEbpClueProductListGetParams|array $params = []): \AdOceanSdk\DPA\Response\DpaEbpClueProductListGetResponse;

    /**
     * 升级版组织-创建/编辑升级版商品
     * https://open.oceanengine.com/labels/7/docs/1846200828633995?origin=left_nav
     */
    public function openDpaEbpClueProductSavePostApi(\AdOceanSdk\DPA\Params\DpaEbpClueProductSavePostParams|array $params = []): \AdOceanSdk\DPA\Response\DpaEbpClueProductSavePostResponse;

    /**
     * 获取商品库DPA词包
     * https://open.oceanengine.com/labels/7/docs/1846199586366875?origin=left_nav
     */
    public function openDpaEbpDictGetGetApi(\AdOceanSdk\DPA\Params\DpaEbpDictGetGetParams|array $params = []): \AdOceanSdk\DPA\Response\DpaEbpDictGetGetResponse;

    /**
     * 获取商品库列表
     * https://open.oceanengine.com/labels/7/docs/1846200555058186?origin=left_nav
     */
    public function openDpaEbpLibraryListGetApi(\AdOceanSdk\DPA\Params\DpaEbpLibraryListGetParams|array $params = []): \AdOceanSdk\DPA\Response\DpaEbpLibraryListGetResponse;

    /**
     * 查询短剧商品原片授权申请状态
     * https://open.oceanengine.com/labels/7/docs/1846199438930378?origin=left_nav
     */
    public function openDpaEbpPlayletAuthGetGetApi(\AdOceanSdk\DPA\Params\DpaEbpPlayletAuthGetGetParams|array $params = []): \AdOceanSdk\DPA\Response\DpaEbpPlayletAuthGetGetResponse;

    /**
     * 升级版组织-新建通用版商品
     * https://open.oceanengine.com/labels/7/docs/1846200859217482?origin=left_nav
     */
    public function openDpaEbpProductCreatePostApi(\AdOceanSdk\DPA\Params\DpaEbpProductCreatePostParams|array $params = []): \AdOceanSdk\DPA\Response\DpaEbpProductCreatePostResponse;

    /**
     * 删除通用版商品
     * https://open.oceanengine.com/labels/7/docs/1846200772027529?origin=left_nav
     */
    public function openDpaEbpProductDeletePostApi(\AdOceanSdk\DPA\Params\DpaEbpProductDeletePostParams|array $params = []): \AdOceanSdk\DPA\Response\DpaEbpProductDeletePostResponse;

    /**
     * 获取通用版商品详情
     * https://open.oceanengine.com/labels/7/docs/1846200441152906?origin=left_nav
     */
    public function openDpaEbpProductDetailGetGetApi(\AdOceanSdk\DPA\Params\DpaEbpProductDetailGetGetParams|array $params = []): \AdOceanSdk\DPA\Response\DpaEbpProductDetailGetGetResponse;

    /**
     * 获取通用版商品列表
     * https://open.oceanengine.com/labels/7/docs/1846200485909513?origin=left_nav
     */
    public function openDpaEbpProductListGetApi(\AdOceanSdk\DPA\Params\DpaEbpProductListGetParams|array $params = []): \AdOceanSdk\DPA\Response\DpaEbpProductListGetResponse;

    /**
     * 批量修改DPA商品状态
     * https://open.oceanengine.com/labels/7/docs/1846200705851659?origin=left_nav
     */
    public function openDpaEbpProductStatusBatchUpdatePostApi(\AdOceanSdk\DPA\Params\DpaEbpProductStatusBatchUpdatePostParams|array $params = []): \AdOceanSdk\DPA\Response\DpaEbpProductStatusBatchUpdatePostResponse;

    /**
     * 升级版组织-编辑通用版商品
     * https://open.oceanengine.com/labels/7/docs/1846200800780617?origin=left_nav
     */
    public function openDpaEbpProductUpdatePostApi(\AdOceanSdk\DPA\Params\DpaEbpProductUpdatePostParams|array $params = []): \AdOceanSdk\DPA\Response\DpaEbpProductUpdatePostResponse;

    /**
     * 获取升级版巨量引擎工作台下账户列表
     * https://open.oceanengine.com/labels/7/docs/1829550825614739?origin=left_nav
     */
    public function openEbpAdvertiserListGetApi(\AdOceanSdk\EBP\Params\EbpAdvertiserListGetParams|array $params = []): \AdOceanSdk\EBP\Response\EbpAdvertiserListGetResponse;

    /**
     * 创建获取升级版巨量引擎工作台账户任务
     * https://open.oceanengine.com/labels/7/docs/1829552494525707?origin=left_nav
     */
    public function openEbpAdvertiserTaskCreatePostApi(\AdOceanSdk\EBP\Params\EbpAdvertiserTaskCreatePostParams|array $params = []): \AdOceanSdk\EBP\Response\EbpAdvertiserTaskCreatePostResponse;

    /**
     * 下载获取升级版巨量引擎工作台账户任务结果
     * https://open.oceanengine.com/labels/7/docs/1829552986209882?origin=left_nav
     */
    public function openEbpAdvertiserTaskDownloadGetApi(\AdOceanSdk\EBP\Params\EbpAdvertiserTaskDownloadGetParams|array $params = []): \AdOceanSdk\EBP\Response\EbpAdvertiserTaskDownloadGetResponse;

    /**
     * 查询获取工作台组织账户任务状态
     * https://open.oceanengine.com/labels/7/docs/1829552777525449?origin=left_nav
     */
    public function openEbpAdvertiserTaskListGetApi(\AdOceanSdk\EBP\Params\EbpAdvertiserTaskListGetParams|array $params = []): \AdOceanSdk\EBP\Response\EbpAdvertiserTaskListGetResponse;

    /**
     * 获取工作台组织关系（升级版）
     * https://open.oceanengine.com/labels/7/docs/1829551362400384?origin=left_nav
     */
    public function openEbpLevelGetGetApi(\AdOceanSdk\EBP\Params\EbpLevelGetGetParams|array $params = []): \AdOceanSdk\EBP\Response\EbpLevelGetGetResponse;

    /**
     * 创建事件资产
     * https://open.oceanengine.com/labels/7/docs/1709792943937547
     */
    public function openEventManagerAssetsCreatePostApi(\AdOceanSdk\Tools\Params\EventManagerAssetsCreatePostParams|array $params = []): \AdOceanSdk\Tools\Response\EventManagerAssetsCreatePostResponse;

    /**
     * 获取可创建事件列表
     * https://open.oceanengine.com/labels/7/docs/1709793059412996
     */
    public function openEventManagerAvailableEventsGetApi(\AdOceanSdk\Tools\Params\EventManagerAvailableEventsGetParams|array $params = []): \AdOceanSdk\Tools\Response\EventManagerAvailableEventsGetResponse;

    /**
     * 获取可用深度优化方式（广告投放升级版）
     * https://open.oceanengine.com/labels/7/docs/1754875889727563
     */
    public function openEventManagerDeepBidTypeGetApi(\AdOceanSdk\Tools\Params\EventManagerDeepBidTypeGetParams|array $params = []): \AdOceanSdk\Tools\Response\EventManagerDeepBidTypeGetResponse;

    /**
     * 获取资产下已创建事件列表
     * https://open.oceanengine.com/labels/7/docs/1709793086075972
     */
    public function openEventManagerEventConfigsGetApi(\AdOceanSdk\Tools\Params\EventManagerEventConfigsGetParams|array $params = []): \AdOceanSdk\Tools\Response\EventManagerEventConfigsGetResponse;

    /**
     * 资产下创建事件
     * https://open.oceanengine.com/labels/7/docs/1709792900524035
     */
    public function openEventManagerEventsCreatePostApi(\AdOceanSdk\Tools\Params\EventManagerEventsCreatePostParams|array $params = []): \AdOceanSdk\Tools\Response\EventManagerEventsCreatePostResponse;

    /**
     * 获取可用优化目标（巨量广告升级版）
     * https://open.oceanengine.com/labels/7/docs/1740944984250381
     */
    public function openEventManagerOptimizedGoalV2GetApi(\AdOceanSdk\Tools\Params\EventManagerOptimizedGoalV2GetParams|array $params = []): \AdOceanSdk\Tools\Response\EventManagerOptimizedGoalV2GetResponse;

    /**
     * 事件管理资产取消共享
     * https://open.oceanengine.com/labels/7/docs/1738862469146628
     */
    public function openEventManagerShareCancelPostApi(\AdOceanSdk\Tools\Params\EventManagerShareCancelPostParams|array $params = []): \AdOceanSdk\Tools\Response\EventManagerShareCancelPostResponse;

    /**
     * 事件管理资产查看共享范围
     * https://open.oceanengine.com/labels/7/docs/1738862504734731
     */
    public function openEventManagerShareGetApi(\AdOceanSdk\Tools\Params\EventManagerShareGetParams|array $params = []): \AdOceanSdk\Tools\Response\EventManagerShareGetResponse;

    /**
     * 事件管理资产共享
     * https://open.oceanengine.com/labels/7/docs/1738862409262084
     */
    public function openEventManagerSharePostApi(\AdOceanSdk\Tools\Params\EventManagerSharePostParams|array $params = []): \AdOceanSdk\Tools\Response\EventManagerSharePostResponse;

    /**
     * 事件资产下创建监测链接组
     * https://open.oceanengine.com/labels/7/docs/1727898582816775
     */
    public function openEventManagerTrackUrlCreatePostApi(\AdOceanSdk\Tools\Params\EventManagerTrackUrlCreatePostParams|array $params = []): \AdOceanSdk\Tools\Response\EventManagerTrackUrlCreatePostResponse;

    /**
     * 获取事件资产下的监测链接组
     * https://open.oceanengine.com/labels/7/docs/1727901957092365
     */
    public function openEventManagerTrackUrlGetApi(\AdOceanSdk\Tools\Params\EventManagerTrackUrlGetParams|array $params = []): \AdOceanSdk\Tools\Response\EventManagerTrackUrlGetResponse;

    /**
     * 事件资产下更新监测链接组
     * https://open.oceanengine.com/labels/7/docs/1727899035395079
     */
    public function openEventManagerTrackUrlUpdatePostApi(\AdOceanSdk\Tools\Params\EventManagerTrackUrlUpdatePostParams|array $params = []): \AdOceanSdk\Tools\Response\EventManagerTrackUrlUpdatePostResponse;

    /**
     * 上传资质图片
     * https://open.oceanengine.com/labels/7/docs/1696710599659532
     */
    public function openFIleImageAdvertiserPostApi(\AdOceanSdk\File\Params\FIleImageAdvertiserPostParams|array $params = []): \AdOceanSdk\File\Response\FIleImageAdvertiserPostResponse;

    /**
     * 上传图文内的音频素材
     * https://open.oceanengine.com/labels/7/docs/1780005237921792
     */
    public function openFileAudioAdPostApi(\AdOceanSdk\File\Params\FileAudioAdPostParams|array $params = []): \AdOceanSdk\File\Response\FileAudioAdPostResponse;

    /**
     * 获取同主体下广告主图片素材
     * https://open.oceanengine.com/labels/7/docs/1696710602952719
     */
    public function openFileImageAdGetApi(\AdOceanSdk\File\Params\FileImageAdGetParams|array $params = []): \AdOceanSdk\File\Response\FileImageAdGetResponse;

    /**
     * 上传广告图片
     * https://open.oceanengine.com/labels/7/docs/1696710600176640
     */
    public function openFileImageAdPostApi(\AdOceanSdk\File\Params\FileImageAdPostParams|array $params = []): \AdOceanSdk\File\Response\FileImageAdPostResponse;

    /**
     * 批量删除图片素材
     * https://open.oceanengine.com/labels/7/docs/1761577471849479
     */
    public function openFileImageDeletePostApi(\AdOceanSdk\File\Params\FileImageDeletePostParams|array $params = []): \AdOceanSdk\File\Response\FileImageDeletePostResponse;

    /**
     * 获取图片素材
     * https://open.oceanengine.com/labels/7/docs/1696710601254912
     */
    public function openFileImageGetApi(\AdOceanSdk\File\Params\FileImageGetParams|array $params = []): \AdOceanSdk\File\Response\FileImageGetResponse;

    /**
     * 获取视频素材评估标签（新版）
     * https://open.oceanengine.com/labels/7/docs/1789500809829388
     */
    public function openFileMaterialAttributesListGetApi(\AdOceanSdk\File\Params\FileMaterialAttributesListGetParams|array $params = []): \AdOceanSdk\File\Response\FileMaterialAttributesListGetResponse;

    /**
     * 素材推送
     * https://open.oceanengine.com/labels/7/docs/1696710604852236
     */
    public function openFileMaterialBindPostApi(\AdOceanSdk\File\Params\FileMaterialBindPostParams|array $params = []): \AdOceanSdk\File\Response\FileMaterialBindPostResponse;

    /**
     * 查询素材标签信息
     * https://open.oceanengine.com/labels/7/docs/1763768835703812
     */
    public function openFileMaterialDetailGetApi(\AdOceanSdk\File\Params\FileMaterialDetailGetParams|array $params = []): \AdOceanSdk\File\Response\FileMaterialDetailGetResponse;

    /**
     * 获取素材标签列表
     * https://open.oceanengine.com/labels/7/docs/1761499216182279
     */
    public function openFileMaterialListGetApi(\AdOceanSdk\File\Params\FileMaterialListGetParams|array $params = []): \AdOceanSdk\File\Response\FileMaterialListGetResponse;

    /**
     * 【代理商】明点无效素材查询
     * https://open.oceanengine.com/labels/7/docs/1779971491239040
     */
    public function openFileRebateMaterialSearchGetApi(\AdOceanSdk\File\Params\FileRebateMaterialSearchGetParams|array $params = []): \AdOceanSdk\File\Response\FileRebateMaterialSearchGetResponse;

    /**
     * 异步上传视频文件
     * https://open.oceanengine.com/labels/7/docs/1801533703648324?origin=left_nav
     */
    public function openFileUploadTaskCreatePostApi(\AdOceanSdk\File\Params\FileUploadTaskCreatePostParams|array $params = []): \AdOceanSdk\File\Response\FileUploadTaskCreatePostResponse;

    /**
     * 获取同主体下广告主视频素材
     * https://open.oceanengine.com/labels/7/docs/1696710603509772
     */
    public function openFileVideoAdGetApi(\AdOceanSdk\File\Params\FileVideoAdGetParams|array $params = []): \AdOceanSdk\File\Response\FileVideoAdGetResponse;

    /**
     * 上传视频
     * https://open.oceanengine.com/labels/7/docs/1696710600730639
     */
    public function openFileVideoAdPostApi(\AdOceanSdk\File\Params\FileVideoAdPostParams|array $params = []): \AdOceanSdk\File\Response\FileVideoAdPostResponse;

    /**
     * 获取抖音主页视频
     * https://open.oceanengine.com/labels/7/docs/1729982871844879
     */
    public function openFileVideoAwemeGetApi(\AdOceanSdk\File\Params\FileVideoAwemeGetParams|array $params = []): \AdOceanSdk\File\Response\FileVideoAwemeGetResponse;

    /**
     * 批量删除视频素材
     * https://open.oceanengine.com/labels/7/docs/1696710605373455
     */
    public function openFileVideoDeletePostApi(\AdOceanSdk\File\Params\FileVideoDeletePostParams|array $params = []): \AdOceanSdk\File\Response\FileVideoDeletePostResponse;

    /**
     * 获取低效素材
     * https://open.oceanengine.com/labels/7/docs/1733880964883467
     */
    public function openFileVideoEfficiencyGetApi(\AdOceanSdk\File\Params\FileVideoEfficiencyGetParams|array $params = []): \AdOceanSdk\File\Response\FileVideoEfficiencyGetResponse;

    /**
     * 获取视频素材
     * https://open.oceanengine.com/labels/7/docs/1696710601820172
     */
    public function openFileVideoGetApi(\AdOceanSdk\File\Params\FileVideoGetParams|array $params = []): \AdOceanSdk\File\Response\FileVideoGetResponse;

    /**
     * 创建素材清理任务
     * https://open.oceanengine.com/labels/7/docs/1764209655140366
     */
    public function openFileVideoMaterialClearTaskCreatePostApi(\AdOceanSdk\File\Params\FileVideoMaterialClearTaskCreatePostParams|array $params = []): \AdOceanSdk\File\Response\FileVideoMaterialClearTaskCreatePostResponse;

    /**
     * 获取清理任务列表
     * https://open.oceanengine.com/labels/7/docs/1764210394714119
     */
    public function openFileVideoMaterialClearTaskGetApi(\AdOceanSdk\File\Params\FileVideoMaterialClearTaskGetParams|array $params = []): \AdOceanSdk\File\Response\FileVideoMaterialClearTaskGetResponse;

    /**
     * 下载清理任务结果
     * https://open.oceanengine.com/labels/7/docs/1764216974179400
     */
    public function openFileVideoMaterialClearTaskResultGetApi(\AdOceanSdk\File\Params\FileVideoMaterialClearTaskResultGetParams|array $params = []): \AdOceanSdk\File\Response\FileVideoMaterialClearTaskResultGetResponse;

    /**
     * 批量暂停素材
     * https://open.oceanengine.com/labels/7/docs/1779985717273613
     */
    public function openFileVideoPausePostApi(\AdOceanSdk\File\Params\FileVideoPausePostParams|array $params = []): \AdOceanSdk\File\Response\FileVideoPausePostResponse;

    /**
     * 更新视频
     * https://open.oceanengine.com/labels/7/docs/1696710605909004
     */
    public function openFileVideoUpdatePostApi(\AdOceanSdk\File\Params\FileVideoUpdatePostParams|array $params = []): \AdOceanSdk\File\Response\FileVideoUpdatePostResponse;

    /**
     * 获取异步上传视频文件结果
     * https://open.oceanengine.com/labels/7/docs/1801544428603604?origin=left_nav
     */
    public function openFileVideoUploadTaskListGetApi(\AdOceanSdk\File\Params\FileVideoUploadTaskListGetParams|array $params = []): \AdOceanSdk\File\Response\FileVideoUploadTaskListGetResponse;

    /**
     * 获取返货共享钱包余额
     * https://open.oceanengine.com/labels/7/docs/1703323812831239
     */
    public function openFundSharedWalletBalanceGetApi(\AdOceanSdk\Fund\Params\FundSharedWalletBalanceGetParams|array $params = []): \AdOceanSdk\Fund\Response\FundSharedWalletBalanceGetResponse;

    /**
     * 获取纵横组织下资产账户列表
     * https://open.oceanengine.com/labels/7/docs/1696710519607296
     */
    public function openMajordomoAdvertiserSelectGetApi(\AdOceanSdk\Majordomo\Params\MajordomoAdvertiserSelectGetParams|array $params = []): \AdOceanSdk\Majordomo\Response\MajordomoAdvertiserSelectGetResponse;

    /**
     * 批量更新广告素材启用状态
     * https://open.oceanengine.com/labels/7/docs/1755355780973568
     */
    public function openMaterialStatusUpdatePostApi(\AdOceanSdk\Advertising\Params\MaterialStatusUpdatePostParams|array $params = []): \AdOceanSdk\Advertising\Response\MaterialStatusUpdatePostResponse;

    /**
     * 创建原生锚点
     * https://open.oceanengine.com/labels/7/docs/1757798123491403
     */
    public function openNativeAnchorCreatePostApi(\AdOceanSdk\Tools\Params\NativeAnchorCreatePostParams|array $params = []): \AdOceanSdk\Tools\Response\NativeAnchorCreatePostResponse;

    /**
     * 删除原生锚点
     * https://open.oceanengine.com/labels/7/docs/1780079261760524
     */
    public function openNativeAnchorDeletePostApi(\AdOceanSdk\Tools\Params\NativeAnchorDeletePostParams|array $params = []): \AdOceanSdk\Tools\Response\NativeAnchorDeletePostResponse;

    /**
     * 获取原生锚点详情
     * https://open.oceanengine.com/labels/7/docs/1786407342576640
     */
    public function openNativeAnchorDetailGetApi(\AdOceanSdk\Tools\Params\NativeAnchorDetailGetParams|array $params = []): \AdOceanSdk\Tools\Response\NativeAnchorDetailGetResponse;

    /**
     * 获取账户下原生锚点
     * https://open.oceanengine.com/labels/7/docs/1757715831323652
     */
    public function openNativeAnchorGetApi(\AdOceanSdk\Tools\Params\NativeAnchorGetParams|array $params = []): \AdOceanSdk\Tools\Response\NativeAnchorGetResponse;

    /**
     * 更新原生锚点
     * https://open.oceanengine.com/labels/7/docs/1780079786680328
     */
    public function openNativeAnchorUpdatePostApi(\AdOceanSdk\Tools\Params\NativeAnchorUpdatePostParams|array $params = []): \AdOceanSdk\Tools\Response\NativeAnchorUpdatePostResponse;

    /**
     * 获取Access Token
     * https://open.oceanengine.com/labels/7/docs/1696710505596940
     */
    public function openOauthAccessTokenGetApi(\AdOceanSdk\Oauth\Params\OauthAccessTokenGetParams|array $params = []): \AdOceanSdk\Oauth\Response\OauthAccessTokenGetResponse;

    /**
     * 获取已授权账户
     * https://open.oceanengine.com/labels/7/docs/1696710506574848
     */
    public function openOauthAdvertiserGetApi(\AdOceanSdk\Oauth\Params\OauthAdvertiserGetParams|array $params = []): \AdOceanSdk\Oauth\Response\OauthAdvertiserGetResponse;

    /**
     * 获取APP Access Token
     * https://open.oceanengine.com/labels/7/docs/1713655428885516
     */
    public function openOauthAppAccessTokenPostApi(\AdOceanSdk\Oauth\Params\OauthAppAccessTokenPostParams|array $params = []): \AdOceanSdk\Oauth\Response\OauthAppAccessTokenPostResponse;

    /**
     * 刷新Refresh Token
     * https://open.oceanengine.com/labels/7/docs/1696710506097679
     */
    public function openOauthRefreshTokenPostApi(\AdOceanSdk\Oauth\Params\OauthRefreshTokenPostParams|array $params = []): \AdOceanSdk\Oauth\Response\OauthRefreshTokenPostResponse;

    /**
     * 获取授权User信息
     * https://open.oceanengine.com/labels/7/docs/1696710507039756
     */
    public function openOauthUserInfoGetApi(\AdOceanSdk\Oauth\Params\OauthUserInfoGetParams|array $params = []): \AdOceanSdk\Oauth\Response\OauthUserInfoGetResponse;

    /**
     * 批量更新项目预算
     * https://open.oceanengine.com/labels/7/docs/1755353873798155
     */
    public function openProjectBudgetUpdatePostApi(\AdOceanSdk\Advertising\Params\ProjectBudgetUpdatePostParams|array $params = []): \AdOceanSdk\Advertising\Response\ProjectBudgetUpdatePostResponse;

    /**
     * 批量更新项目出价NEW
     * https://open.oceanengine.com/labels/34/docs/1858174581876745?origin=left_nav
     */
    public function openProjectCpaBidUpdatePostApi(\AdOceanSdk\Advertising\Params\ProjectCpaBidUpdatePostParams|array $params = []): \AdOceanSdk\Advertising\Response\ProjectCpaBidUpdatePostResponse;

    /**
     * 创建项目
     * https://open.oceanengine.com/labels/7/docs/1740868093375503
     */
    public function openProjectCreatePostApi(\AdOceanSdk\Advertising\Params\ProjectCreatePostParams|array $params = []): \AdOceanSdk\Advertising\Response\ProjectCreatePostResponse;

    /**
     * 批量更新深层项目出价NEW
     * https://open.oceanengine.com/labels/34/docs/1858175093068809?origin=left_nav
     */
    public function openProjectDeepCpaBidUpdatePostApi(\AdOceanSdk\Advertising\Params\ProjectDeepCpaBidUpdatePostParams|array $params = []): \AdOceanSdk\Advertising\Response\ProjectDeepCpaBidUpdatePostResponse;

    /**
     * 批量删除项目
     * https://open.oceanengine.com/labels/7/docs/1740944781036608
     */
    public function openProjectDeletePostApi(\AdOceanSdk\Advertising\Params\ProjectDeletePostParams|array $params = []): \AdOceanSdk\Advertising\Response\ProjectDeletePostResponse;

    /**
     * 获取项目列表
     * https://open.oceanengine.com/labels/7/docs/1740937147595776
     */
    public function openProjectListGetApi(\AdOceanSdk\Advertising\Params\ProjectListGetParams|array $params = []): \AdOceanSdk\Advertising\Response\ProjectListGetResponse;

    /**
     * 获取投放项目审核建议
     * https://open.oceanengine.com/labels/7/docs/1854930234989579
     */
    public function openProjectRejectReasonGetApi(\AdOceanSdk\OcProject\Params\ProjectRejectReasonGetParams|array $params = []): \AdOceanSdk\OcProject\Response\ProjectRejectReasonGetResponse;

    /**
     * 批量修改项目ROI系数
     * https://open.oceanengine.com/labels/34/docs/1794208148473859?origin=left_nav
     */
    public function openProjectRoigoalUpdatePostApi(\AdOceanSdk\Advertising\Params\ProjectRoigoalUpdatePostParams|array $params = []): \AdOceanSdk\Advertising\Response\ProjectRoigoalUpdatePostResponse;

    /**
     * 批量更新项目投放时间
     * https://open.oceanengine.com/labels/7/docs/1779258970970184
     */
    public function openProjectScheduleTimeUpdatePostApi(\AdOceanSdk\Advertising\Params\ProjectScheduleTimeUpdatePostParams|array $params = []): \AdOceanSdk\Advertising\Response\ProjectScheduleTimeUpdatePostResponse;

    /**
     * 批量更新项目状态
     * https://open.oceanengine.com/labels/7/docs/1740941413906432
     */
    public function openProjectStatusUpdatePostApi(\AdOceanSdk\Advertising\Params\ProjectStatusUpdatePostParams|array $params = []): \AdOceanSdk\Advertising\Response\ProjectStatusUpdatePostResponse;

    /**
     * 更新项目
     * https://open.oceanengine.com/labels/7/docs/1740936504522831
     */
    public function openProjectUpdatePostApi(\AdOceanSdk\Advertising\Params\ProjectUpdatePostParams|array $params = []): \AdOceanSdk\Advertising\Response\ProjectUpdatePostResponse;

    /**
     * 批量更新项目投放时段
     * https://open.oceanengine.com/labels/7/docs/1779260654537728
     */
    public function openProjectWeekScheduleUpdatePostApi(\AdOceanSdk\Advertising\Params\ProjectWeekScheduleUpdatePostParams|array $params = []): \AdOceanSdk\Advertising\Response\ProjectWeekScheduleUpdatePostResponse;

    /**
     * 新建/修改白盒配置（广告升级版）
     * https://open.oceanengine.com/labels/7/docs/1760943644787716
     */
    public function openPromotionAutoGenerateConfigCreatePostApi(\AdOceanSdk\Advertising\Params\PromotionAutoGenerateConfigCreatePostParams|array $params = []): \AdOceanSdk\Advertising\Response\PromotionAutoGenerateConfigCreatePostResponse;

    /**
     * 查询配置详情（广告升级版）
     * https://open.oceanengine.com/labels/7/docs/1760943993851915
     */
    public function openPromotionAutoGenerateConfigGetApi(\AdOceanSdk\Advertising\Params\PromotionAutoGenerateConfigGetParams|array $params = []): \AdOceanSdk\Advertising\Response\PromotionAutoGenerateConfigGetResponse;

    /**
     * 批量更新广告出价
     * https://open.oceanengine.com/labels/7/docs/1741031138305028
     */
    public function openPromotionBidUpdatePostApi(\AdOceanSdk\Advertising\Params\PromotionBidUpdatePostParams|array $params = []): \AdOceanSdk\Advertising\Response\PromotionBidUpdatePostResponse;

    /**
     * 批量更新广告预算
     * https://open.oceanengine.com/labels/7/docs/1741030872454148
     */
    public function openPromotionBudgetUpdatePostApi(\AdOceanSdk\Advertising\Params\PromotionBudgetUpdatePostParams|array $params = []): \AdOceanSdk\Advertising\Response\PromotionBudgetUpdatePostResponse;

    /**
     * 批量获取广告成本保障状态
     * https://open.oceanengine.com/labels/7/docs/1755355980850191
     */
    public function openPromotionCostProtectStatusGetApi(\AdOceanSdk\Advertising\Params\PromotionCostProtectStatusGetParams|array $params = []): \AdOceanSdk\Advertising\Response\PromotionCostProtectStatusGetResponse;

    /**
     * 创建广告
     * https://open.oceanengine.com/labels/7/docs/1740946299496459
     */
    public function openPromotionCreatePostApi(\AdOceanSdk\Advertising\Params\PromotionCreatePostParams|array $params = []): \AdOceanSdk\Advertising\Response\PromotionCreatePostResponse;

    /**
     * 批量修改深度出价
     * https://open.oceanengine.com/labels/7/docs/1755355890182159
     */
    public function openPromotionDeepBidUpdatePostApi(\AdOceanSdk\Advertising\Params\PromotionDeepBidUpdatePostParams|array $params = []): \AdOceanSdk\Advertising\Response\PromotionDeepBidUpdatePostResponse;

    /**
     * 批量删除广告
     * https://open.oceanengine.com/labels/7/docs/1741031376580675
     */
    public function openPromotionDeletePostApi(\AdOceanSdk\Advertising\Params\PromotionDeletePostParams|array $params = []): \AdOceanSdk\Advertising\Response\PromotionDeletePostResponse;

    /**
     * 获取广告列表
     * https://open.oceanengine.com/labels/7/docs/1741028841006095
     */
    public function openPromotionListGetApi(\AdOceanSdk\Advertising\Params\PromotionListGetParams|array $params = []): \AdOceanSdk\Advertising\Response\PromotionListGetResponse;

    /**
     * 批量获取广告审核建议
     * https://open.oceanengine.com/labels/7/docs/1741031528693771
     */
    public function openPromotionRejectReasonGetApi(\AdOceanSdk\Advertising\Params\PromotionRejectReasonGetParams|array $params = []): \AdOceanSdk\Advertising\Response\PromotionRejectReasonGetResponse;

    /**
     * 批量更新广告投放时段
     * https://open.oceanengine.com/labels/7/docs/1769912402184199
     */
    public function openPromotionScheduleTimeUpdatePostApi(\AdOceanSdk\Advertising\Params\PromotionScheduleTimeUpdatePostParams|array $params = []): \AdOceanSdk\Advertising\Response\PromotionScheduleTimeUpdatePostResponse;

    /**
     * 批量更新广告启用状态
     * https://open.oceanengine.com/labels/7/docs/1741031308559364
     */
    public function openPromotionStatusUpdatePostApi(\AdOceanSdk\Advertising\Params\PromotionStatusUpdatePostParams|array $params = []): \AdOceanSdk\Advertising\Response\PromotionStatusUpdatePostResponse;

    /**
     * 修改广告
     * https://open.oceanengine.com/labels/7/docs/1740952287987719
     */
    public function openPromotionUpdatePostApi(\AdOceanSdk\Advertising\Params\PromotionUpdatePostParams|array $params = []): \AdOceanSdk\Advertising\Response\PromotionUpdatePostResponse;

    /**
     * 广告主数据
     * https://open.oceanengine.com/labels/7/docs/1696710550620160
     */
    public function openReportAdvertiserGetApi(\AdOceanSdk\Report\Params\ReportAdvertiserGetParams|array $params = []): \AdOceanSdk\Report\Response\ReportAdvertiserGetResponse;

    /**
     * 广告组数据
     * https://open.oceanengine.com/labels/7/docs/1696710551161856
     */
    public function openReportCampaignGetApi(\AdOceanSdk\Report\Params\ReportCampaignGetParams|array $params = []): \AdOceanSdk\Report\Response\ReportCampaignGetResponse;

    /**
     * 广告创意数据
     * https://open.oceanengine.com/labels/7/docs/1696710552261644
     */
    public function openReportCreativeGetApi(\AdOceanSdk\Report\Params\ReportCreativeGetParams|array $params = []): \AdOceanSdk\Report\Response\ReportCreativeGetResponse;

    /**
     * 获取自定义报表可用指标和维度
     * https://open.oceanengine.com/labels/7/docs/1755261744248832
     */
    public function openReportCustomConfigGetApi(\AdOceanSdk\Report\Params\ReportCustomConfigGetParams|array $params = []): \AdOceanSdk\Report\Response\ReportCustomConfigGetResponse;

    /**
     * 自定义报表
     * https://open.oceanengine.com/labels/7/docs/1741387668314126
     */
    public function openReportCustomGetApi(\AdOceanSdk\Report\Params\ReportCustomGetParams|array $params = []): \AdOceanSdk\Report\Response\ReportCustomGetResponse;

    /**
     * 多合一数据报表接口
     * https://open.oceanengine.com/labels/7/docs/1696710554400780
     */
    public function openReportIntergratedGetApi(\AdOceanSdk\Report\Params\ReportIntergratedGetParams|array $params = []): \AdOceanSdk\Report\Response\ReportIntergratedGetResponse;

    /**
     * 橙子建站落地页数据
     * https://open.oceanengine.com/labels/7/docs/1696710565390348
     */
    public function openReportSitePageGetApi(\AdOceanSdk\Report\Params\ReportSitePageGetParams|array $params = []): \AdOceanSdk\Report\Response\ReportSitePageGetResponse;

    /**
     * 资金共享-共享钱包信息查询
     * https://open.oceanengine.com/labels/7/docs/1798465885126668
     */
    public function openSharedWalletMainWalletGetApi(\AdOceanSdk\Fund\Params\SharedWalletMainWalletGetParams|array $params = []): \AdOceanSdk\Fund\Response\SharedWalletMainWalletGetResponse;

    /**
     * 基于站点创建模板
     * https://open.oceanengine.com/labels/7/docs/1722273160450059
     */
    public function openSiteTemplateCreatePostApi(\AdOceanSdk\Tools\Params\SiteTemplateCreatePostParams|array $params = []): \AdOceanSdk\Tools\Response\SiteTemplateCreatePostResponse;

    /**
     * 获取站点模版列表
     * https://open.oceanengine.com/labels/7/docs/1722273219292292
     */
    public function openSiteTemplateGetApi(\AdOceanSdk\Tools\Params\SiteTemplateGetParams|array $params = []): \AdOceanSdk\Tools\Response\SiteTemplateGetResponse;

    /**
     * 获取模板/站点URL
     * https://open.oceanengine.com/labels/7/docs/1772995231995911
     */
    public function openSiteTemplatePicUrlGetApi(\AdOceanSdk\Tools\Params\SiteTemplatePicUrlGetParams|array $params = []): \AdOceanSdk\Tools\Response\SiteTemplatePicUrlGetResponse;

    /**
     * 获取模版预览链接
     * https://open.oceanengine.com/labels/7/docs/1722273233146891
     */
    public function openSiteTemplatePreviewGetApi(\AdOceanSdk\Tools\Params\SiteTemplatePreviewGetParams|array $params = []): \AdOceanSdk\Tools\Response\SiteTemplatePreviewGetResponse;

    /**
     * 基于模板创建站点
     * https://open.oceanengine.com/labels/7/docs/1722273197263875
     */
    public function openSiteTemplateSiteCreatePostApi(\AdOceanSdk\Tools\Params\SiteTemplateSiteCreatePostParams|array $params = []): \AdOceanSdk\Tools\Response\SiteTemplateSiteCreatePostResponse;

    /**
     * 行动号召字段内容获取
     * https://open.oceanengine.com/labels/7/docs/1696710684229644
     */
    public function openToolsActionTextGetApi(\AdOceanSdk\Tools\Params\ToolsActionTextGetParams|array $params = []): \AdOceanSdk\Tools\Response\ToolsActionTextGetResponse;

    /**
     * 获取广告预览二维码（升级版）
     * https://open.oceanengine.com/labels/7/docs/1763117461145604
     */
    public function openToolsAdPreviewQrcodeGetApi(\AdOceanSdk\Tools\Params\ToolsAdPreviewQrcodeGetParams|array $params = []): \AdOceanSdk\Tools\Response\ToolsAdPreviewQrcodeGetResponse;

    /**
     * 查询广告质量度
     * https://open.oceanengine.com/labels/7/docs/1696710677262351
     */
    public function openToolsAdQualityGetApi(\AdOceanSdk\Tools\Params\ToolsAdQualityGetParams|array $params = []): \AdOceanSdk\Tools\Response\ToolsAdQualityGetResponse;

    /**
     * 查询广告计划学习期状态
     * https://open.oceanengine.com/labels/7/docs/1696710684841984
     */
    public function openToolsAdStatExtraInfoGetApi(\AdOceanSdk\Tools\Params\ToolsAdStatExtraInfoGetParams|array $params = []): \AdOceanSdk\Tools\Response\ToolsAdStatExtraInfoGetResponse;

    /**
     * 获取行政信息
     * https://open.oceanengine.com/labels/7/docs/1709606596424718
     */
    public function openToolsAdminInfoGetApi(\AdOceanSdk\Tools\Params\ToolsAdminInfoGetParams|array $params = []): \AdOceanSdk\Tools\Response\ToolsAdminInfoGetResponse;

    /**
     * 获取字节小程序/小游戏详情内容
     * https://open.oceanengine.com/labels/7/docs/1778265753535620
     */
    public function openToolsAssetLinkListGetApi(\AdOceanSdk\Tools\Params\ToolsAssetLinkListGetParams|array $params = []): \AdOceanSdk\Tools\Response\ToolsAssetLinkListGetResponse;

    /**
     * 获取抖音授权关系
     * https://open.oceanengine.com/labels/7/docs/1729983667746823
     */
    public function openToolsAwemeAuthListGetApi(\AdOceanSdk\Tools\Params\ToolsAwemeAuthListGetParams|array $params = []): \AdOceanSdk\Tools\Response\ToolsAwemeAuthListGetResponse;

    /**
     * 建议日预算及预期成本
     * https://open.oceanengine.com/labels/7/docs/1696710676657164
     */
    public function openToolsBidSuggestGetApi(\AdOceanSdk\Tools\Params\ToolsBidSuggestGetParams|array $params = []): \AdOceanSdk\Tools\Response\ToolsBidSuggestGetResponse;

    /**
     * 查询建议出价（巨量广告升级版）
     * https://open.oceanengine.com/labels/7/docs/1771363823169544
     */
    public function openToolsBidsSuggestGetApi(\AdOceanSdk\Tools\Params\ToolsBidsSuggestGetParams|array $params = []): \AdOceanSdk\Tools\Response\ToolsBidsSuggestGetResponse;

    /**
     * 取消微信小游戏/小程序共享关系
     * https://open.oceanengine.com/labels/7/docs/1773102677218368
     */
    public function openToolsBpAssetManagementShareCancelPostApi(\AdOceanSdk\Tools\Params\ToolsBpAssetManagementShareCancelPostParams|array $params = []): \AdOceanSdk\Tools\Response\ToolsBpAssetManagementShareCancelPostResponse;

    /**
     * 查看微信小游戏/小程序共享范围
     * https://open.oceanengine.com/labels/7/docs/1773105971421187
     */
    public function openToolsBpAssetManagementShareGetApi(\AdOceanSdk\Tools\Params\ToolsBpAssetManagementShareGetParams|array $params = []): \AdOceanSdk\Tools\Response\ToolsBpAssetManagementShareGetResponse;

    /**
     * 设置微信小游戏/小程序共享
     * https://open.oceanengine.com/labels/7/docs/1773089427219584
     */
    public function openToolsBpAssetManagementSharePostApi(\AdOceanSdk\Tools\Params\ToolsBpAssetManagementSharePostParams|array $params = []): \AdOceanSdk\Tools\Response\ToolsBpAssetManagementSharePostResponse;

    /**
     * 回传有效线索
     * https://open.oceanengine.com/labels/7/docs/1696710631812096
     */
    public function openToolsClueCallbackPostApi(\AdOceanSdk\Tools\Params\ToolsClueCallbackPostParams|array $params = []): \AdOceanSdk\Tools\Response\ToolsClueCallbackPostResponse;

    /**
     * 获取线索列表
     * https://open.oceanengine.com/labels/7/docs/1696710631271436
     */
    public function openToolsClueGetApi(\AdOceanSdk\Tools\Params\ToolsClueGetParams|array $params = []): \AdOceanSdk\Tools\Response\ToolsClueGetResponse;

    /**
     * 获取评论列表
     * https://open.oceanengine.com/labels/7/docs/1754803808580608
     */
    public function openToolsCommentGetApi(\AdOceanSdk\Tools\Params\ToolsCommentGetParams|array $params = []): \AdOceanSdk\Tools\Response\ToolsCommentGetResponse;

    /**
     * 隐藏评论
     * https://open.oceanengine.com/labels/7/docs/1754804147204108
     */
    public function openToolsCommentHidePostApi(\AdOceanSdk\Tools\Params\ToolsCommentHidePostParams|array $params = []): \AdOceanSdk\Tools\Response\ToolsCommentHidePostResponse;

    /**
     * 获取评论统计指标
     * https://open.oceanengine.com/labels/7/docs/1779551814119427
     */
    public function openToolsCommentMetricsGetApi(\AdOceanSdk\Tools\Params\ToolsCommentMetricsGetParams|array $params = []): \AdOceanSdk\Tools\Response\ToolsCommentMetricsGetResponse;

    /**
     * 获取评论视频ID列表
     * https://open.oceanengine.com/labels/7/docs/1773084580896776
     */
    public function openToolsCommentMid2itemIdGetApi(\AdOceanSdk\Tools\Params\ToolsCommentMid2itemIdGetParams|array $params = []): \AdOceanSdk\Tools\Response\ToolsCommentMid2itemIdGetResponse;

    /**
     * 回复评论
     * https://open.oceanengine.com/labels/7/docs/1754803971592192
     */
    public function openToolsCommentReplyPostApi(\AdOceanSdk\Tools\Params\ToolsCommentReplyPostParams|array $params = []): \AdOceanSdk\Tools\Response\ToolsCommentReplyPostResponse;

    /**
     * 查询国家/区域信息
     * https://open.oceanengine.com/labels/7/docs/1709606374050823
     */
    public function openToolsCountryInfoGetApi(\AdOceanSdk\Tools\Params\ToolsCountryInfoGetParams|array $params = []): \AdOceanSdk\Tools\Response\ToolsCountryInfoGetResponse;

    /**
     * 创建动态创意词包
     * https://open.oceanengine.com/labels/7/docs/1696710717478927
     */
    public function openToolsCreativeWordCreatePostApi(\AdOceanSdk\Tools\Params\ToolsCreativeWordCreatePostParams|array $params = []): \AdOceanSdk\Tools\Response\ToolsCreativeWordCreatePostResponse;

    /**
     * 删除动态创意词包
     * https://open.oceanengine.com/labels/7/docs/1696710719368207
     */
    public function openToolsCreativeWordDeletePostApi(\AdOceanSdk\Tools\Params\ToolsCreativeWordDeletePostParams|array $params = []): \AdOceanSdk\Tools\Response\ToolsCreativeWordDeletePostResponse;

    /**
     * 查询动态创意词包
     * https://open.oceanengine.com/labels/7/docs/1696710718137356
     */
    public function openToolsCreativeWordSelectGetApi(\AdOceanSdk\Tools\Params\ToolsCreativeWordSelectGetParams|array $params = []): \AdOceanSdk\Tools\Response\ToolsCreativeWordSelectGetResponse;

    /**
     * 更新动态创意词包
     * https://open.oceanengine.com/labels/7/docs/1696710718730240
     */
    public function openToolsCreativeWordUpdatePostApi(\AdOceanSdk\Tools\Params\ToolsCreativeWordUpdatePostParams|array $params = []): \AdOceanSdk\Tools\Response\ToolsCreativeWordUpdatePostResponse;

    /**
     * 取消资产共享
     * https://open.oceanengine.com/labels/7/docs/1848328204842138?origin=left_nav
     */
    public function openToolsEbpAssetAuthCancelPostApi(\AdOceanSdk\Tools\Params\ToolsEbpAssetAuthCancelPostParams|array $params = []): \AdOceanSdk\Tools\Response\ToolsEbpAssetAuthCancelPostResponse;

    /**
     * 查询资产共享范围
     * https://open.oceanengine.com/labels/7/docs/1848326390305163?origin=left_nav
     */
    public function openToolsEbpAssetAuthListGetApi(\AdOceanSdk\Tools\Params\ToolsEbpAssetAuthListGetParams|array $params = []): \AdOceanSdk\Tools\Response\ToolsEbpAssetAuthListGetResponse;

    /**
     * 添加资产共享
     * https://open.oceanengine.com/labels/7/docs/1848327327721671?origin=left_nav
     */
    public function openToolsEbpAssetAuthPostApi(\AdOceanSdk\Tools\Params\ToolsEbpAssetAuthPostParams|array $params = []): \AdOceanSdk\Tools\Response\ToolsEbpAssetAuthPostResponse;

    /**
     * 升级版工作台素材共享
     * https://open.oceanengine.com/labels/7/docs/1854120947746880?origin=left_nav
     */
    public function openToolsEbpMaterialAuthCreatePostApi(\AdOceanSdk\Tools\Params\ToolsEbpMaterialAuthCreatePostParams|array $params = []): \AdOceanSdk\Tools\Response\ToolsEbpMaterialAuthCreatePostResponse;

    /**
     * 升级版工作台取消素材共享
     * https://open.oceanengine.com/labels/7/docs/1855452458903624?origin=left_nav
     */
    public function openToolsEbpMaterialAuthDeletePostApi(\AdOceanSdk\Tools\Params\ToolsEbpMaterialAuthDeletePostParams|array $params = []): \AdOceanSdk\Tools\Response\ToolsEbpMaterialAuthDeletePostResponse;

    /**
     * 升级版工作台查询素材共享范围
     * https://open.oceanengine.com/labels/7/docs/1855451294366919?origin=left_nav
     */
    public function openToolsEbpMaterialAuthListGetApi(\AdOceanSdk\Tools\Params\ToolsEbpMaterialAuthListGetParams|array $params = []): \AdOceanSdk\Tools\Response\ToolsEbpMaterialAuthListGetResponse;

    /**
     * 新建字节小程序
     * https://open.oceanengine.com/labels/7/docs/1847487532455299?origin=left_nav
     */
    public function openToolsEbpMicroAppletCreatePostApi(\AdOceanSdk\Tools\Params\ToolsEbpMicroAppletCreatePostParams|array $params = []): \AdOceanSdk\Tools\Response\ToolsEbpMicroAppletCreatePostResponse;

    /**
     * 获取字节小程序link详情
     * https://open.oceanengine.com/labels/7/docs/1847487745198092?origin=left_nav
     */
    public function openToolsEbpMicroAppletLinkListGetApi(\AdOceanSdk\Tools\Params\ToolsEbpMicroAppletLinkListGetParams|array $params = []): \AdOceanSdk\Tools\Response\ToolsEbpMicroAppletLinkListGetResponse;

    /**
     * 获取字节小程序列表
     * https://open.oceanengine.com/labels/7/docs/1847487562418308?origin=left_nav
     */
    public function openToolsEbpMicroAppletListGetApi(\AdOceanSdk\Tools\Params\ToolsEbpMicroAppletListGetParams|array $params = []): \AdOceanSdk\Tools\Response\ToolsEbpMicroAppletListGetResponse;

    /**
     * 更新字节小程序
     * https://open.oceanengine.com/labels/7/docs/1847487541689347?origin=left_nav
     */
    public function openToolsEbpMicroAppletUpdatePostApi(\AdOceanSdk\Tools\Params\ToolsEbpMicroAppletUpdatePostParams|array $params = []): \AdOceanSdk\Tools\Response\ToolsEbpMicroAppletUpdatePostResponse;

    /**
     * 获取字节小游戏链接详情
     * https://open.oceanengine.com/labels/7/docs/1847487751501836?origin=left_nav
     */
    public function openToolsEbpMicroGameLinkListGetApi(\AdOceanSdk\Tools\Params\ToolsEbpMicroGameLinkListGetParams|array $params = []): \AdOceanSdk\Tools\Response\ToolsEbpMicroGameLinkListGetResponse;

    /**
     * 获取组织认证及授权主体列表NEW
     * https://open.oceanengine.com/labels/7/docs/1855089467521035?origin=left_nav
     */
    public function openToolsEbpSubjectListGetApi(\AdOceanSdk\Tools\Params\ToolsEbpSubjectListGetParams|array $params = []): \AdOceanSdk\Tools\Response\ToolsEbpSubjectListGetResponse;

    /**
     * 升级版工作台获取视频素材评估标签
     * https://open.oceanengine.com/labels/7/docs/1855453250877440?origin=left_nav
     */
    public function openToolsEbpVideoAttributesListGetApi(\AdOceanSdk\Tools\Params\ToolsEbpVideoAttributesListGetParams|array $params = []): \AdOceanSdk\Tools\Response\ToolsEbpVideoAttributesListGetResponse;

    /**
     * 升级版工作台批量删除视频
     * https://open.oceanengine.com/labels/7/docs/1855450454372428?origin=left_nav
     */
    public function openToolsEbpVideoDeletePostApi(\AdOceanSdk\Tools\Params\ToolsEbpVideoDeletePostParams|array $params = []): \AdOceanSdk\Tools\Response\ToolsEbpVideoDeletePostResponse;

    /**
     * 升级版工作台更新视频
     * https://open.oceanengine.com/labels/7/docs/1855449500037184?origin=left_nav
     */
    public function openToolsEbpVideoUpdatePostApi(\AdOceanSdk\Tools\Params\ToolsEbpVideoUpdatePostParams|array $params = []): \AdOceanSdk\Tools\Response\ToolsEbpVideoUpdatePostResponse;

    /**
     * 升级版工作台上传视频
     * https://open.oceanengine.com/labels/7/docs/1855448450527623?origin=left_nav
     */
    public function openToolsEbpVideoUploadPostApi(\AdOceanSdk\Tools\Params\ToolsEbpVideoUploadPostParams|array $params = []): \AdOceanSdk\Tools\Response\ToolsEbpVideoUploadPostResponse;

    /**
     * 新建微信小程序
     * https://open.oceanengine.com/labels/7/docs/1847487724040192?origin=left_nav
     */
    public function openToolsEbpWechatAppletCreatePostApi(\AdOceanSdk\Tools\Params\ToolsEbpWechatAppletCreatePostParams|array $params = []): \AdOceanSdk\Tools\Response\ToolsEbpWechatAppletCreatePostResponse;

    /**
     * 获取微信小程序列表
     * https://open.oceanengine.com/labels/7/docs/1847487716271104?origin=left_nav
     */
    public function openToolsEbpWechatAppletListGetApi(\AdOceanSdk\Tools\Params\ToolsEbpWechatAppletListGetParams|array $params = []): \AdOceanSdk\Tools\Response\ToolsEbpWechatAppletListGetResponse;

    /**
     * 更新微信小程序
     * https://open.oceanengine.com/labels/7/docs/1847487757321420?origin=left_nav
     */
    public function openToolsEbpWechatAppletUpdatePostApi(\AdOceanSdk\Tools\Params\ToolsEbpWechatAppletUpdatePostParams|array $params = []): \AdOceanSdk\Tools\Response\ToolsEbpWechatAppletUpdatePostResponse;

    /**
     * 查询受众预估结果
     * https://open.oceanengine.com/labels/7/docs/1696710675422208
     */
    public function openToolsEstimateAudienceGetApi(\AdOceanSdk\Tools\Params\ToolsEstimateAudienceGetParams|array $params = []): \AdOceanSdk\Tools\Response\ToolsEstimateAudienceGetResponse;

    /**
     * 获取预估点击成本
     * https://open.oceanengine.com/labels/7/docs/1717213696709710
     */
    public function openToolsEstimatedPriceGetApi(\AdOceanSdk\Tools\Params\ToolsEstimatedPriceGetParams|array $params = []): \AdOceanSdk\Tools\Response\ToolsEstimatedPriceGetResponse;

    /**
     * 获取已创建资产详情（新）
     * https://open.oceanengine.com/labels/7/docs/1800988620664954
     */
    public function openToolsEventAllAssetsDetailGetApi(\AdOceanSdk\Tools\Params\ToolsEventAllAssetsDetailGetParams|array $params = []): \AdOceanSdk\Tools\Response\ToolsEventAllAssetsDetailGetResponse;

    /**
     * 获取账户下资产列表（新）
     * https://open.oceanengine.com/labels/7/docs/1800985709803914
     */
    public function openToolsEventAllAssetsListGetApi(\AdOceanSdk\Tools\Params\ToolsEventAllAssetsListGetParams|array $params = []): \AdOceanSdk\Tools\Response\ToolsEventAllAssetsListGetResponse;

    /**
     * 获取已创建资产列表
     * https://open.oceanengine.com/labels/7/docs/1705976384784395
     */
    public function openToolsEventAssetsGetApi(\AdOceanSdk\Tools\Params\ToolsEventAssetsGetParams|array $params = []): \AdOceanSdk\Tools\Response\ToolsEventAssetsGetResponse;

    /**
     * 获取活动记录
     * https://open.oceanengine.com/labels/7/docs/1696710632392704
     */
    public function openToolsKeyActionGetApi(\AdOceanSdk\Tools\Params\ToolsKeyActionGetParams|array $params = []): \AdOceanSdk\Tools\Response\ToolsKeyActionGetResponse;

    /**
     * 创建落地页组
     * https://open.oceanengine.com/labels/7/docs/1696710628472844
     */
    public function openToolsLandingGroupCreatePostApi(\AdOceanSdk\Tools\Params\ToolsLandingGroupCreatePostParams|array $params = []): \AdOceanSdk\Tools\Response\ToolsLandingGroupCreatePostResponse;

    /**
     * 获取落地页组
     * https://open.oceanengine.com/labels/7/docs/1696710629043212
     */
    public function openToolsLandingGroupGetApi(\AdOceanSdk\Tools\Params\ToolsLandingGroupGetParams|array $params = []): \AdOceanSdk\Tools\Response\ToolsLandingGroupGetResponse;

    /**
     * 更新落地页组站点状态
     * https://open.oceanengine.com/labels/7/docs/1696710629600256
     */
    public function openToolsLandingGroupSiteOptStatusUpdatePostApi(\AdOceanSdk\Tools\Params\ToolsLandingGroupSiteOptStatusUpdatePostParams|array $params = []): \AdOceanSdk\Tools\Response\ToolsLandingGroupSiteOptStatusUpdatePostResponse;

    /**
     * 更新落地页组信息
     * https://open.oceanengine.com/labels/7/docs/1696710630182912
     */
    public function openToolsLandingGroupUpdatePostApi(\AdOceanSdk\Tools\Params\ToolsLandingGroupUpdatePostParams|array $params = []): \AdOceanSdk\Tools\Response\ToolsLandingGroupUpdatePostResponse;

    /**
     * 日志查询
     * https://open.oceanengine.com/labels/7/docs/1696710682956815
     */
    public function openToolsLogSearchGetApi(\AdOceanSdk\Tools\Params\ToolsLogSearchGetParams|array $params = []): \AdOceanSdk\Tools\Response\ToolsLogSearchGetResponse;

    /**
     * 创建字节小程序
     * https://open.oceanengine.com/labels/7/docs/1780613896121344
     */
    public function openToolsMicroAppCreatePostApi(\AdOceanSdk\Tools\Params\ToolsMicroAppCreatePostParams|array $params = []): \AdOceanSdk\Tools\Response\ToolsMicroAppCreatePostResponse;

    /**
     * 获取字节小程序
     * https://open.oceanengine.com/labels/7/docs/1778249831680135
     */
    public function openToolsMicroAppListGetApi(\AdOceanSdk\Tools\Params\ToolsMicroAppListGetParams|array $params = []): \AdOceanSdk\Tools\Response\ToolsMicroAppListGetResponse;

    /**
     * 更新字节小程序
     * https://open.oceanengine.com/labels/7/docs/1780614097935372
     */
    public function openToolsMicroAppUpdatePostApi(\AdOceanSdk\Tools\Params\ToolsMicroAppUpdatePostParams|array $params = []): \AdOceanSdk\Tools\Response\ToolsMicroAppUpdatePostResponse;

    /**
     * 通过优化目标获取橙子落地页站点信息
     * https://open.oceanengine.com/labels/7/docs/1755162848410635
     */
    public function openToolsOrangeSiteGetApi(\AdOceanSdk\Tools\Params\ToolsOrangeSiteGetParams|array $params = []): \AdOceanSdk\Tools\Response\ToolsOrangeSiteGetResponse;

    /**
     * 素材前置预审结果获取
     * https://open.oceanengine.com/labels/7/docs/1722273278471172
     */
    public function openToolsPreAuditGetApi(\AdOceanSdk\Tools\Params\ToolsPreAuditGetParams|array $params = []): \AdOceanSdk\Tools\Response\ToolsPreAuditGetResponse;

    /**
     * 素材前置预审送审
     * https://open.oceanengine.com/labels/7/docs/1722273263150083
     */
    public function openToolsPreAuditSendPostApi(\AdOceanSdk\Tools\Params\ToolsPreAuditSendPostParams|array $params = []): \AdOceanSdk\Tools\Response\ToolsPreAuditSendPostResponse;

    /**
     * 采纳广告诊断建议
     * https://open.oceanengine.com/labels/7/docs/1754716131916803
     */
    public function openToolsPromotionDiagnosisSuggestionAcceptPostApi(\AdOceanSdk\Tools\Params\ToolsPromotionDiagnosisSuggestionAcceptPostParams|array $params = []): \AdOceanSdk\Tools\Response\ToolsPromotionDiagnosisSuggestionAcceptPostResponse;

    /**
     * 获取广告诊断建议
     * https://open.oceanengine.com/labels/7/docs/1754715780584459
     */
    public function openToolsPromotionDiagnosisSuggestionGetApi(\AdOceanSdk\Tools\Params\ToolsPromotionDiagnosisSuggestionGetParams|array $params = []): \AdOceanSdk\Tools\Response\ToolsPromotionDiagnosisSuggestionGetResponse;

    /**
     * 开启/更新一键起量
     * https://open.oceanengine.com/labels/7/docs/1761603589597259
     */
    public function openToolsPromotionRaiseSetPostApi(\AdOceanSdk\Tools\Params\ToolsPromotionRaiseSetPostParams|array $params = []): \AdOceanSdk\Tools\Response\ToolsPromotionRaiseSetPostResponse;

    /**
     * 获取广告起量状态
     * https://open.oceanengine.com/labels/7/docs/1765406483367948
     */
    public function openToolsPromotionRaiseStatusCurrentIdsGetApi(\AdOceanSdk\Tools\Params\ToolsPromotionRaiseStatusCurrentIdsGetParams|array $params = []): \AdOceanSdk\Tools\Response\ToolsPromotionRaiseStatusCurrentIdsGetResponse;

    /**
     * 获取一键起量方案列表
     * https://open.oceanengine.com/labels/7/docs/1761603513577476
     */
    public function openToolsPromotionRaiseStatusGetApi(\AdOceanSdk\Tools\Params\ToolsPromotionRaiseStatusGetParams|array $params = []): \AdOceanSdk\Tools\Response\ToolsPromotionRaiseStatusGetResponse;

    /**
     * 关停正在起量的广告
     * https://open.oceanengine.com/labels/7/docs/1761603666011139
     */
    public function openToolsPromotionRaiseStopPostApi(\AdOceanSdk\Tools\Params\ToolsPromotionRaiseStopPostParams|array $params = []): \AdOceanSdk\Tools\Response\ToolsPromotionRaiseStopPostResponse;

    /**
     * 获取起量版本信息
     * https://open.oceanengine.com/labels/7/docs/1761603462670403
     */
    public function openToolsPromotionRaiseVersionGetApi(\AdOceanSdk\Tools\Params\ToolsPromotionRaiseVersionGetParams|array $params = []): \AdOceanSdk\Tools\Response\ToolsPromotionRaiseVersionGetResponse;

    /**
     * 查询在投计划配额
     * https://open.oceanengine.com/labels/7/docs/1731070251873293
     */
    public function openToolsQuotaGetApi(\AdOceanSdk\Tools\Params\ToolsQuotaGetParams|array $params = []): \AdOceanSdk\Tools\Response\ToolsQuotaGetResponse;

    /**
     * 获取地域列表
     * https://open.oceanengine.com/labels/7/docs/1696710678458380
     */
    public function openToolsRegionGetApi(\AdOceanSdk\Tools\Params\ToolsRegionGetParams|array $params = []): \AdOceanSdk\Tools\Response\ToolsRegionGetResponse;

    /**
     * 获取快投推荐出价系数
     * https://open.oceanengine.com/labels/7/docs/1740289237468175
     */
    public function openToolsSearchBidRatioGetApi(\AdOceanSdk\Tools\Params\ToolsSearchBidRatioGetParams|array $params = []): \AdOceanSdk\Tools\Response\ToolsSearchBidRatioGetResponse;

    /**
     * 建站工具-建站复制
     * https://open.oceanengine.com/labels/7/docs/1696710623908864
     */
    public function openToolsSiteCopyPostApi(\AdOceanSdk\Tools\Params\ToolsSiteCopyPostParams|array $params = []): \AdOceanSdk\Tools\Response\ToolsSiteCopyPostResponse;

    /**
     * 创建橙子建站站点
     * https://open.oceanengine.com/labels/7/docs/1696710617712640
     */
    public function openToolsSiteCreatePostApi(\AdOceanSdk\Tools\Params\ToolsSiteCreatePostParams|array $params = []): \AdOceanSdk\Tools\Response\ToolsSiteCreatePostResponse;

    /**
     * 获取橙子建站站点列表
     * https://open.oceanengine.com/labels/7/docs/1696710620579852
     */
    public function openToolsSiteGetApi(\AdOceanSdk\Tools\Params\ToolsSiteGetParams|array $params = []): \AdOceanSdk\Tools\Response\ToolsSiteGetResponse;

    /**
     * 建站工具-建站转赠
     * https://open.oceanengine.com/labels/7/docs/1696710623352844
     */
    public function openToolsSiteHandselPostApi(\AdOceanSdk\Tools\Params\ToolsSiteHandselPostParams|array $params = []): \AdOceanSdk\Tools\Response\ToolsSiteHandselPostResponse;

    /**
     * 获取橙子建站站点预览地址
     * https://open.oceanengine.com/labels/7/docs/1696710619437056
     */
    public function openToolsSitePreviewGetApi(\AdOceanSdk\Tools\Params\ToolsSitePreviewGetParams|array $params = []): \AdOceanSdk\Tools\Response\ToolsSitePreviewGetResponse;

    /**
     * 获取橙子建站站点详细信息
     * https://open.oceanengine.com/labels/7/docs/1696710620022799
     */
    public function openToolsSiteReadGetApi(\AdOceanSdk\Tools\Params\ToolsSiteReadGetParams|array $params = []): \AdOceanSdk\Tools\Response\ToolsSiteReadGetResponse;

    /**
     * 修改橙子建站站点
     * https://open.oceanengine.com/labels/7/docs/1696710618300431
     */
    public function openToolsSiteUpdatePostApi(\AdOceanSdk\Tools\Params\ToolsSiteUpdatePostParams|array $params = []): \AdOceanSdk\Tools\Response\ToolsSiteUpdatePostResponse;

    /**
     * 更改橙子建站站点状态
     * https://open.oceanengine.com/labels/7/docs/1696710618884096
     */
    public function openToolsSiteUpdateStatusPostApi(\AdOceanSdk\Tools\Params\ToolsSiteUpdateStatusPostParams|array $params = []): \AdOceanSdk\Tools\Response\ToolsSiteUpdateStatusPostResponse;

    /**
     * 获取广告建议起量预算
     * https://open.oceanengine.com/labels/7/docs/1761603631358979
     */
    public function openToolsSuggestBudgetGetApi(\AdOceanSdk\Tools\Params\ToolsSuggestBudgetGetParams|array $params = []): \AdOceanSdk\Tools\Response\ToolsSuggestBudgetGetResponse;

    /**
     * 获取视频智能封面
     * https://open.oceanengine.com/labels/7/docs/1696710602404864
     */
    public function openToolsVideoCoverSuggestGetApi(\AdOceanSdk\Tools\Params\ToolsVideoCoverSuggestGetParams|array $params = []): \AdOceanSdk\Tools\Response\ToolsVideoCoverSuggestGetResponse;

    /**
     * 创建微信小程序
     * https://open.oceanengine.com/labels/7/docs/1771744149686286
     */
    public function openToolsWechatAppletCreatePostApi(\AdOceanSdk\Tools\Params\ToolsWechatAppletCreatePostParams|array $params = []): \AdOceanSdk\Tools\Response\ToolsWechatAppletCreatePostResponse;

    /**
     * 获取微信小程序列表
     * https://open.oceanengine.com/labels/7/docs/1771203622020111
     */
    public function openToolsWechatAppletListGetApi(\AdOceanSdk\Tools\Params\ToolsWechatAppletListGetParams|array $params = []): \AdOceanSdk\Tools\Response\ToolsWechatAppletListGetResponse;

    /**
     * 更新微信小程序
     * https://open.oceanengine.com/labels/7/docs/1771744756803659
     */
    public function openToolsWechatAppletUpdatePostApi(\AdOceanSdk\Tools\Params\ToolsWechatAppletUpdatePostParams|array $params = []): \AdOceanSdk\Tools\Response\ToolsWechatAppletUpdatePostResponse;

    /**
     * 获取全域创编可用抖音号
     * https://open.oceanengine.com/labels/7/docs/1854930373174281
     */
    public function openUniProjectAwemeAuthorizedGetApi(\AdOceanSdk\UNI\Params\UniProjectAwemeAuthorizedGetParams|array $params = []): \AdOceanSdk\UNI\Response\UniProjectAwemeAuthorizedGetResponse;

    /**
     * 新建全域投放项目
     * https://open.oceanengine.com/labels/7/docs/1854206019149016
     */
    public function openUniProjectCreatePostApi(\AdOceanSdk\UNI\Params\UniProjectCreatePostParams|array $params = []): \AdOceanSdk\UNI\Response\UniProjectCreatePostResponse;

    /**
     * 获取全域投放项目列表
     * https://open.oceanengine.com/labels/7/docs/1854926110406984
     */
    public function openUniProjectListGetApi(\AdOceanSdk\UNI\Params\UniProjectListGetParams|array $params = []): \AdOceanSdk\UNI\Response\UniProjectListGetResponse;

    /**
     * 获取全域投放项目列表
     * https://open.oceanengine.com/labels/7/docs/1854926110406984
     */
    public function openUniProjectListGetGetApi(\AdOceanSdk\UNI\Params\UniProjectListGetGetParams|array $params = []): \AdOceanSdk\UNI\Response\UniProjectListGetGetResponse;

    /**
     * 编辑全域投放项目
     * https://open.oceanengine.com/labels/7/docs/1854910852321354
     */
    public function openUniProjectUpdatePostApi(\AdOceanSdk\UNI\Params\UniProjectUpdatePostParams|array $params = []): \AdOceanSdk\UNI\Response\UniProjectUpdatePostResponse;

    /**
     * 获取微信小程序列表
     * https://open.oceanengine.com/labels/7/docs/1771203622020111
     */
    public function openWechatAppletListGetApi(\AdOceanSdk\Tools\Params\WechatAppletListGetParams|array $params = []): \AdOceanSdk\Tools\Response\WechatAppletListGetResponse;
}
