<?php

declare(strict_types=1);

namespace AdOceanSdk\Script\Generator;

use RuntimeException;

final class OpenApiAnnotationGenerator
{
    public function generateFromConfig(
        array $config,
        string $sourceFile,
        ?string $outputFile = null,
        ?string $traitFile = null,
        ?string $interfaceFile = null,
    ): void {
        $outputFile ??= $sourceFile;
        $traitFile ??= dirname($outputFile) . '/OpenApiMethodsTrait.php';
        $interfaceFile ??= dirname($outputFile) . '/Kernel/Interface/OpenApiInterface.php';

        $sourceCode = file_get_contents($sourceFile);
        if ($sourceCode === false) {
            throw new RuntimeException("Unable to read source file: {$sourceFile}");
        }

        $namespace          = $this->extractNamespace($sourceCode);
        $traitName          = pathinfo($traitFile, PATHINFO_FILENAME);
        $interfaceName      = pathinfo($interfaceFile, PATHINFO_FILENAME);
        $interfaceNamespace = $this->guessInterfaceNamespace($namespace, $interfaceFile, $outputFile);

        $traitCode     = $this->buildTraitCode($config, $namespace, $traitName);
        $interfaceCode = $this->buildInterfaceCode($config, $interfaceNamespace, $interfaceName);
        $updatedCode   = $this->syncOpenApiClass($sourceCode, $traitName);

        $this->writeIfChanged($traitFile, $traitCode);
        $this->writeIfChanged($interfaceFile, $interfaceCode);

        if ($updatedCode === $sourceCode) {
            return;
        }

        file_put_contents($outputFile, $updatedCode);
    }

    private function writeIfChanged(string $path, string $content): void
    {
        $dir = dirname($path);
        if (!is_dir($dir)) {
            mkdir($dir, 0777, true);
        }
        $existing = file_exists($path) ? file_get_contents($path) : false;
        if ($existing !== $content) {
            file_put_contents($path, $content);
        }
    }

    private function guessInterfaceNamespace(string $sourceNamespace, string $interfaceFile, string $sourceFile): string
    {
        $sourceDir    = realpath(dirname($sourceFile)) ?: dirname($sourceFile);
        $interfaceDir = realpath(dirname($interfaceFile)) ?: dirname($interfaceFile);

        if ($sourceDir === $interfaceDir) {
            return $sourceNamespace;
        }

        if (str_starts_with($interfaceDir, $sourceDir)) {
            $suffix = trim(substr($interfaceDir, strlen($sourceDir)), DIRECTORY_SEPARATOR);
            if ($suffix === '') {
                return $sourceNamespace;
            }
            return $sourceNamespace . '\\' . str_replace(DIRECTORY_SEPARATOR, '\\', $suffix);
        }

        return $sourceNamespace . '\\Kernel\\Interface';
    }

    public function buildTraitCode(array $config, string $namespace, string $traitName = 'OpenApiMethodsTrait'): string
    {
        ksort($config);

        $methods = '';

        foreach ($config as $apiName => $apiData) {
            $desc = $this->normalizeCommentText((string) ($apiData['desc'] ?? ''));
            $doc = $this->normalizeCommentText((string) ($apiData['doc'] ?? ''));
            $response = ltrim((string) ($apiData['response'] ?? 'AdOceanSdk\\RequestResponse'), '\\');
            $params = ltrim((string) ($apiData['params'] ?? 'AdOceanSdk\\RequestParams'), '\\');

            $methods .= "\n    /**\n"
                . "     * {$desc}\n"
                . "     * {$doc}\n"
                . "     */\n"
                . "    public function {$apiName}(\\{$params}|array \$params = []): \\{$response}\n"
                . "    {\n"
                . "        /** @var \\{$response} \$response */\n"
                . "        \$response = \$this->callApi(__FUNCTION__, \$params);\n\n"
                . "        return \$response;\n"
                . "    }\n";
        }

        return "<?php\n\n"
            . "namespace {$namespace};\n\n"
            . "/**\n"
            . " * OpenApi generated methods.\n"
            . " * @generated by script/gen_api_open.php\n"
            . " */\n"
            . "trait {$traitName}\n"
            . "{"
            . $methods
            . "}\n";
    }

    public function buildInterfaceCode(array $config, string $namespace, string $interfaceName = 'OpenApiInterface'): string
    {
        ksort($config);

        $methods = '';

        foreach ($config as $apiName => $apiData) {
            $desc = $this->normalizeCommentText((string) ($apiData['desc'] ?? ''));
            $doc = $this->normalizeCommentText((string) ($apiData['doc'] ?? ''));
            $response = ltrim((string) ($apiData['response'] ?? 'AdOceanSdk\\RequestResponse'), '\\');
            $params = ltrim((string) ($apiData['params'] ?? 'AdOceanSdk\\RequestParams'), '\\');

            $methods .= "\n    /**\n"
                . "     * {$desc}\n"
                . "     * {$doc}\n"
                . "     */\n"
                . "    public function {$apiName}(\\{$params}|array \$params = []): \\{$response};\n";
        }

        return "<?php\n\n"
            . "namespace {$namespace};\n\n"
            . "/**\n"
            . " * OpenApi public surface — generated.\n"
            . " * Implemented by \\AdOceanSdk\\OpenApi via OpenApiMethodsTrait.\n"
            . " * @generated by script/gen_api_open.php\n"
            . " */\n"
            . "interface {$interfaceName}\n"
            . "{"
            . $methods
            . "}\n";
    }

    private function syncOpenApiClass(string $sourceCode, string $traitName): string
    {
        $docblock = $this->buildClassDocblock($traitName);

        $patternWithDocblock = '/\/\*\*[\s\S]*?\*\/\s*(class\s+OpenApi\b)/';
        $replacement = $docblock . "\n" . '$1';

        $updatedCode = preg_replace($patternWithDocblock, $replacement, $sourceCode, 1, $count);
        if ($updatedCode === null) {
            throw new RuntimeException('Failed to replace OpenApi docblock.');
        }

        if ($count === 1) {
            return $this->ensureTraitUse($updatedCode, $traitName);
        }

        $patternWithoutDocblock = '/(class\s+OpenApi\b)/';
        $updatedCode = preg_replace($patternWithoutDocblock, $docblock . "\n" . '$1', $sourceCode, 1, $count);
        if ($updatedCode === null || $count === 0) {
            throw new RuntimeException('Unable to locate OpenApi class for annotation generation.');
        }

        return $this->ensureTraitUse($updatedCode, $traitName);
    }

    private function buildClassDocblock(string $traitName): string
    {
        return "/**\n"
            . " * class OpenApi\n"
            . " * 开放接口调度类\n"
            . " * @see {$traitName}\n"
            . " */";
    }

    private function ensureTraitUse(string $sourceCode, string $traitName): string
    {
        $updatedCode = preg_replace(
            '/(class\s+OpenApi\b[^\{]*\{\R)(?:\h*use\s+' . preg_quote($traitName, '/') . ';\R\R)?/',
            '$1' . "    use {$traitName};\n\n",
            $sourceCode,
            1,
            $count
        );

        if ($updatedCode === null || $count === 0) {
            throw new RuntimeException('Unable to inject OpenApi methods trait usage.');
        }

        $updatedCode = preg_replace(
            '/(use\s+' . preg_quote($traitName, '/') . ';\R\R)(?=(private|protected|public|function|\/\*\*))/m',
            '$1    ',
            $updatedCode,
            1
        );

        if ($updatedCode === null) {
            throw new RuntimeException('Unable to normalize OpenApi member indentation after trait injection.');
        }

        return $updatedCode;
    }

    private function extractNamespace(string $sourceCode): string
    {
        if (preg_match('/^namespace\s+(.+);/m', $sourceCode, $matches) !== 1) {
            throw new RuntimeException('Unable to detect namespace for OpenApi file.');
        }

        return trim($matches[1]);
    }

    private function normalizeCommentText(string $text): string
    {
        return trim(str_replace(["\r", "\n"], ' ', $text));
    }
}